import { DevotionalContent, AppSettings } from './types';

export const FALLBACK_DEVOTIONAL: DevotionalContent = {
  title: "The Steady Walk",
  scripture: {
    text: "For we walk by faith, not by sight.",
    reference: "2 Corinthians 5:7"
  },
  reflection: "Our journey with Christ is often less about the destination and more about the daily rhythm of trust. Each step we take in faith draws us closer to His heart, and closer to the people He has placed in our path. Walking by faith means trusting God even when the way ahead is unclear, knowing that His plans are perfect and His timing is sure. Like a child trusting their parent's hand in the dark, we lean into God's character, not our circumstances.",
  prayer: "Lord, help me to walk by faith today. When I cannot see the path ahead, remind me that You hold my future. Guide my steps, quiet my fears, and let my life be a testimony of Your faithfulness. In Jesus name, Amen.",
  stepOfFaith: "Take a 10-minute prayer walk today, asking God to guide your steps.",
  tags: ["faith", "trust", "daily walk", "courage"]
};

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'light',
  fontSize: 18,
  fontFamily: 'Lora',
  defaultBibleVersion: 'KJV',
  language: 'en',
  animationsEnabled: true,
  footstepAnimation: true,
  showVerseNumbers: true,
  dyslexiaFriendly: false,
  highContrast: false,
  largeText: false,
};

export const CLAUDE_API_KEY = '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';

export const BIBLE_BOOKS_FULL = [
  { name: 'Genesis', category: 'Law', chapters: 50, testament: 'OT', abbr: 'Gen' },
  { name: 'Exodus', category: 'Law', chapters: 40, testament: 'OT', abbr: 'Exo' },
  { name: 'Leviticus', category: 'Law', chapters: 27, testament: 'OT', abbr: 'Lev' },
  { name: 'Numbers', category: 'Law', chapters: 36, testament: 'OT', abbr: 'Num' },
  { name: 'Deuteronomy', category: 'Law', chapters: 34, testament: 'OT', abbr: 'Deu' },
  { name: 'Joshua', category: 'History', chapters: 24, testament: 'OT', abbr: 'Jos' },
  { name: 'Judges', category: 'History', chapters: 21, testament: 'OT', abbr: 'Jdg' },
  { name: 'Ruth', category: 'History', chapters: 4, testament: 'OT', abbr: 'Rut' },
  { name: '1 Samuel', category: 'History', chapters: 31, testament: 'OT', abbr: '1Sa' },
  { name: '2 Samuel', category: 'History', chapters: 24, testament: 'OT', abbr: '2Sa' },
  { name: '1 Kings', category: 'History', chapters: 22, testament: 'OT', abbr: '1Ki' },
  { name: '2 Kings', category: 'History', chapters: 25, testament: 'OT', abbr: '2Ki' },
  { name: '1 Chronicles', category: 'History', chapters: 29, testament: 'OT', abbr: '1Ch' },
  { name: '2 Chronicles', category: 'History', chapters: 36, testament: 'OT', abbr: '2Ch' },
  { name: 'Ezra', category: 'History', chapters: 10, testament: 'OT', abbr: 'Ezr' },
  { name: 'Nehemiah', category: 'History', chapters: 13, testament: 'OT', abbr: 'Neh' },
  { name: 'Esther', category: 'History', chapters: 10, testament: 'OT', abbr: 'Est' },
  { name: 'Job', category: 'Poetry', chapters: 42, testament: 'OT', abbr: 'Job' },
  { name: 'Psalms', category: 'Poetry', chapters: 150, testament: 'OT', abbr: 'Psa' },
  { name: 'Proverbs', category: 'Poetry', chapters: 31, testament: 'OT', abbr: 'Pro' },
  { name: 'Ecclesiastes', category: 'Poetry', chapters: 12, testament: 'OT', abbr: 'Ecc' },
  { name: 'Song of Solomon', category: 'Poetry', chapters: 8, testament: 'OT', abbr: 'Son' },
  { name: 'Isaiah', category: 'Major Prophets', chapters: 66, testament: 'OT', abbr: 'Isa' },
  { name: 'Jeremiah', category: 'Major Prophets', chapters: 52, testament: 'OT', abbr: 'Jer' },
  { name: 'Lamentations', category: 'Major Prophets', chapters: 5, testament: 'OT', abbr: 'Lam' },
  { name: 'Ezekiel', category: 'Major Prophets', chapters: 48, testament: 'OT', abbr: 'Eze' },
  { name: 'Daniel', category: 'Major Prophets', chapters: 12, testament: 'OT', abbr: 'Dan' },
  { name: 'Hosea', category: 'Minor Prophets', chapters: 14, testament: 'OT', abbr: 'Hos' },
  { name: 'Joel', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Joe' },
  { name: 'Amos', category: 'Minor Prophets', chapters: 9, testament: 'OT', abbr: 'Amo' },
  { name: 'Obadiah', category: 'Minor Prophets', chapters: 1, testament: 'OT', abbr: 'Oba' },
  { name: 'Jonah', category: 'Minor Prophets', chapters: 4, testament: 'OT', abbr: 'Jon' },
  { name: 'Micah', category: 'Minor Prophets', chapters: 7, testament: 'OT', abbr: 'Mic' },
  { name: 'Nahum', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Nah' },
  { name: 'Habakkuk', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Hab' },
  { name: 'Zephaniah', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Zep' },
  { name: 'Haggai', category: 'Minor Prophets', chapters: 2, testament: 'OT', abbr: 'Hag' },
  { name: 'Zechariah', category: 'Minor Prophets', chapters: 14, testament: 'OT', abbr: 'Zec' },
  { name: 'Malachi', category: 'Minor Prophets', chapters: 4, testament: 'OT', abbr: 'Mal' },
  { name: 'Matthew', category: 'Gospels', chapters: 28, testament: 'NT', abbr: 'Mat' },
  { name: 'Mark', category: 'Gospels', chapters: 16, testament: 'NT', abbr: 'Mar' },
  { name: 'Luke', category: 'Gospels', chapters: 24, testament: 'NT', abbr: 'Luk' },
  { name: 'John', category: 'Gospels', chapters: 21, testament: 'NT', abbr: 'Joh' },
  { name: 'Acts', category: 'Acts', chapters: 28, testament: 'NT', abbr: 'Act' },
  { name: 'Romans', category: 'Epistles', chapters: 16, testament: 'NT', abbr: 'Rom' },
  { name: '1 Corinthians', category: 'Epistles', chapters: 16, testament: 'NT', abbr: '1Co' },
  { name: '2 Corinthians', category: 'Epistles', chapters: 13, testament: 'NT', abbr: '2Co' },
  { name: 'Galatians', category: 'Epistles', chapters: 6, testament: 'NT', abbr: 'Gal' },
  { name: 'Ephesians', category: 'Epistles', chapters: 6, testament: 'NT', abbr: 'Eph' },
  { name: 'Philippians', category: 'Epistles', chapters: 4, testament: 'NT', abbr: 'Phi' },
  { name: 'Colossians', category: 'Epistles', chapters: 4, testament: 'NT', abbr: 'Col' },
  { name: '1 Thessalonians', category: 'Epistles', chapters: 5, testament: 'NT', abbr: '1Th' },
  { name: '2 Thessalonians', category: 'Epistles', chapters: 3, testament: 'NT', abbr: '2Th' },
  { name: '1 Timothy', category: 'Epistles', chapters: 6, testament: 'NT', abbr: '1Ti' },
  { name: '2 Timothy', category: 'Epistles', chapters: 4, testament: 'NT', abbr: '2Ti' },
  { name: 'Titus', category: 'Epistles', chapters: 3, testament: 'NT', abbr: 'Tit' },
  { name: 'Philemon', category: 'Epistles', chapters: 1, testament: 'NT', abbr: 'Phm' },
  { name: 'Hebrews', category: 'General Epistles', chapters: 13, testament: 'NT', abbr: 'Heb' },
  { name: 'James', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: 'Jam' },
  { name: '1 Peter', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: '1Pe' },
  { name: '2 Peter', category: 'General Epistles', chapters: 3, testament: 'NT', abbr: '2Pe' },
  { name: '1 John', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: '1Jo' },
  { name: '2 John', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: '2Jo' },
  { name: '3 John', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: '3Jo' },
  { name: 'Jude', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: 'Jud' },
  { name: 'Revelation', category: 'Revelation', chapters: 22, testament: 'NT', abbr: 'Rev' },
];

export const COMPREHENSIVE_BIBLE_VERSIONS = [
  // ── ENGLISH ──────────────────────────────────────────────────────────────
  { id: 'KJV',     name: 'King James Version',              abbreviation: 'KJV',     language: 'English',    languageCode: 'en', year: 1611, type: 'formal',   region: 'Global' },
  { id: 'NKJV',   name: 'New King James Version',          abbreviation: 'NKJV',   language: 'English',    languageCode: 'en', year: 1982, type: 'formal',   region: 'Global' },
  { id: 'ESV',    name: 'English Standard Version',         abbreviation: 'ESV',    language: 'English',    languageCode: 'en', year: 2001, type: 'formal',   region: 'Global' },
  { id: 'NIV',    name: 'New International Version',        abbreviation: 'NIV',    language: 'English',    languageCode: 'en', year: 1978, type: 'dynamic',  region: 'Global' },
  { id: 'NIV2011',name: 'New International Version 2011',   abbreviation: 'NIV',    language: 'English',    languageCode: 'en', year: 2011, type: 'dynamic',  region: 'Global' },
  { id: 'NLT',    name: 'New Living Translation',           abbreviation: 'NLT',    language: 'English',    languageCode: 'en', year: 1996, type: 'dynamic',  region: 'Global' },
  { id: 'MSG',    name: 'The Message',                      abbreviation: 'MSG',    language: 'English',    languageCode: 'en', year: 2002, type: 'paraphrase',region: 'Global' },
  { id: 'AMP',    name: 'Amplified Bible',                  abbreviation: 'AMP',    language: 'English',    languageCode: 'en', year: 1965, type: 'expanded', region: 'Global' },
  { id: 'AMPC',   name: 'Amplified Bible Classic',          abbreviation: 'AMPC',   language: 'English',    languageCode: 'en', year: 1965, type: 'expanded', region: 'Global' },
  { id: 'NASB',   name: 'New American Standard Bible 1995', abbreviation: 'NASB',   language: 'English',    languageCode: 'en', year: 1995, type: 'formal',   region: 'Global' },
  { id: 'NASB2020',name: 'New American Standard Bible 2020',abbreviation: 'NASB20', language: 'English',    languageCode: 'en', year: 2020, type: 'formal',   region: 'Global' },
  { id: 'CSB',    name: 'Christian Standard Bible',         abbreviation: 'CSB',    language: 'English',    languageCode: 'en', year: 2017, type: 'formal',   region: 'Global' },
  { id: 'HCSB',   name: 'Holman Christian Standard Bible',  abbreviation: 'HCSB',   language: 'English',    languageCode: 'en', year: 1999, type: 'formal',   region: 'Global' },
  { id: 'RSV',    name: 'Revised Standard Version',         abbreviation: 'RSV',    language: 'English',    languageCode: 'en', year: 1952, type: 'formal',   region: 'Global' },
  { id: 'NRSV',   name: 'New Revised Standard Version',     abbreviation: 'NRSV',   language: 'English',    languageCode: 'en', year: 1989, type: 'formal',   region: 'Global' },
  { id: 'NRSVue', name: 'New Revised Standard Version Updated',abbreviation: 'NRSVue',language: 'English', languageCode: 'en', year: 2021, type: 'formal',   region: 'Global' },
  { id: 'GNT',    name: 'Good News Translation',            abbreviation: 'GNT',    language: 'English',    languageCode: 'en', year: 1976, type: 'dynamic',  region: 'Global' },
  { id: 'CEV',    name: 'Contemporary English Version',     abbreviation: 'CEV',    language: 'English',    languageCode: 'en', year: 1995, type: 'dynamic',  region: 'Global' },
  { id: 'WEB',    name: 'World English Bible',              abbreviation: 'WEB',    language: 'English',    languageCode: 'en', year: 2000, type: 'formal',   region: 'Global' },
  { id: 'LEB',    name: 'Lexham English Bible',             abbreviation: 'LEB',    language: 'English',    languageCode: 'en', year: 2011, type: 'formal',   region: 'Global' },
  { id: 'TLB',    name: 'The Living Bible',                 abbreviation: 'TLB',    language: 'English',    languageCode: 'en', year: 1971, type: 'paraphrase',region: 'Global' },
  { id: 'ASV',    name: 'American Standard Version',        abbreviation: 'ASV',    language: 'English',    languageCode: 'en', year: 1901, type: 'formal',   region: 'Global' },
  { id: 'YLT',    name: 'Young\'s Literal Translation',     abbreviation: 'YLT',    language: 'English',    languageCode: 'en', year: 1862, type: 'literal',  region: 'Global' },
  { id: 'Darby',  name: 'Darby Translation',                abbreviation: 'DBY',    language: 'English',    languageCode: 'en', year: 1890, type: 'formal',   region: 'Global' },
  { id: 'WYC',    name: 'Wycliffe Bible',                   abbreviation: 'WYC',    language: 'English',    languageCode: 'en', year: 1395, type: 'historical',region: 'Global' },
  { id: 'Geneva', name: 'Geneva Bible',                     abbreviation: 'GNV',    language: 'English',    languageCode: 'en', year: 1560, type: 'historical',region: 'Global' },
  { id: 'Coverdale',name: 'Coverdale Bible',                abbreviation: 'CVD',    language: 'English',    languageCode: 'en', year: 1535, type: 'historical',region: 'Global' },
  { id: 'DouayRheims',name: 'Douay-Rheims Bible',           abbreviation: 'DRA',    language: 'English',    languageCode: 'en', year: 1610, type: 'formal',   region: 'Global' },
  { id: 'VOICE',  name: 'The Voice',                        abbreviation: 'VOICE',  language: 'English',    languageCode: 'en', year: 2012, type: 'dynamic',  region: 'Global' },
  { id: 'EXB',    name: 'Expanded Bible',                   abbreviation: 'EXB',    language: 'English',    languageCode: 'en', year: 2011, type: 'expanded', region: 'Global' },
  { id: 'NET',    name: 'New English Translation',          abbreviation: 'NET',    language: 'English',    languageCode: 'en', year: 2005, type: 'formal',   region: 'Global' },
  { id: 'ISV',    name: 'International Standard Version',   abbreviation: 'ISV',    language: 'English',    languageCode: 'en', year: 2014, type: 'formal',   region: 'Global' },
  { id: 'NABRE',  name: 'New American Bible Revised Edition',abbreviation: 'NABRE', language: 'English',    languageCode: 'en', year: 2011, type: 'formal',   region: 'Global' },
  { id: 'NCV',    name: 'New Century Version',              abbreviation: 'NCV',    language: 'English',    languageCode: 'en', year: 1987, type: 'dynamic',  region: 'Global' },
  { id: 'ICB',    name: "International Children's Bible",   abbreviation: 'ICB',    language: 'English',    languageCode: 'en', year: 1986, type: 'dynamic',  region: 'Global' },
  { id: 'NIRV',   name: "New International Reader's Version",abbreviation: 'NIrV',  language: 'English',    languageCode: 'en', year: 1994, type: 'dynamic',  region: 'Global' },
  { id: 'ERV',    name: 'Easy-to-Read Version',             abbreviation: 'ERV',    language: 'English',    languageCode: 'en', year: 2006, type: 'dynamic',  region: 'Global' },
  { id: 'CJB',    name: 'Complete Jewish Bible',            abbreviation: 'CJB',    language: 'English',    languageCode: 'en', year: 1998, type: 'formal',   region: 'Global' },
  { id: 'TLV',    name: 'Tree of Life Version',             abbreviation: 'TLV',    language: 'English',    languageCode: 'en', year: 2015, type: 'formal',   region: 'Global' },
  { id: 'OJB',    name: 'Orthodox Jewish Bible',            abbreviation: 'OJB',    language: 'English',    languageCode: 'en', year: 2002, type: 'formal',   region: 'Global' },
  { id: 'PHILLIPS',name: 'J.B. Phillips New Testament',     abbreviation: 'PHILLIPS',language: 'English',   languageCode: 'en', year: 1958, type: 'paraphrase',region: 'Global' },
  { id: 'WNT',    name: 'Weymouth New Testament',           abbreviation: 'WNT',    language: 'English',    languageCode: 'en', year: 1903, type: 'formal',   region: 'Global' },
  { id: 'MOUNCE', name: 'Mounce Reverse Interlinear NT',    abbreviation: 'MRC',    language: 'English',    languageCode: 'en', year: 2011, type: 'interlinear',region: 'Global' },
  { id: 'BRG',    name: 'BRG Bible',                        abbreviation: 'BRG',    language: 'English',    languageCode: 'en', year: 2012, type: 'formal',   region: 'Global' },

  // ── SPANISH ──────────────────────────────────────────────────────────────
  { id: 'RV1909', name: 'Reina Valera 1909',                abbreviation: 'RV1909', language: 'Spanish',    languageCode: 'es', year: 1909, type: 'formal',   region: 'Latin America' },
  { id: 'RV1960', name: 'Reina Valera 1960',                abbreviation: 'RVR60', language: 'Spanish',    languageCode: 'es', year: 1960, type: 'formal',   region: 'Latin America' },
  { id: 'RV1995', name: 'Reina Valera 1995',                abbreviation: 'RVR95', language: 'Spanish',    languageCode: 'es', year: 1995, type: 'formal',   region: 'Latin America' },
  { id: 'NVI',    name: 'Nueva Versión Internacional',       abbreviation: 'NVI',    language: 'Spanish',    languageCode: 'es', year: 1999, type: 'dynamic',  region: 'Latin America' },
  { id: 'BLPH',   name: 'La Palabra de Dios para Todos',    abbreviation: 'PDT',    language: 'Spanish',    languageCode: 'es', year: 2012, type: 'dynamic',  region: 'Latin America' },
  { id: 'CST',    name: 'Castilian Spanish',                abbreviation: 'CST',    language: 'Spanish (Spain)',languageCode: 'es', year: 2010, type: 'formal', region: 'Spain' },
  { id: 'NBD',    name: 'Nueva Biblia al Día',              abbreviation: 'NBD',    language: 'Spanish',    languageCode: 'es', year: 2008, type: 'dynamic',  region: 'Latin America' },
  { id: 'LBLA',   name: 'La Biblia de las Americas',        abbreviation: 'LBLA',   language: 'Spanish',    languageCode: 'es', year: 1986, type: 'formal',   region: 'Latin America' },
  { id: 'DHH',    name: 'Dios Habla Hoy',                   abbreviation: 'DHH',    language: 'Spanish',    languageCode: 'es', year: 1979, type: 'dynamic',  region: 'Latin America' },
  { id: 'TLA',    name: 'Traducción en Lenguaje Actual',    abbreviation: 'TLA',    language: 'Spanish',    languageCode: 'es', year: 2003, type: 'dynamic',  region: 'Latin America' },
  { id: 'BLP',    name: 'La Palabra (Spain)',               abbreviation: 'BLP',    language: 'Spanish',    languageCode: 'es', year: 2010, type: 'dynamic',  region: 'Spain' },
  { id: 'RVR2000',name: 'Reina Valera 2000',                abbreviation: 'RVR2000',language: 'Spanish',    languageCode: 'es', year: 2000, type: 'formal',   region: 'Latin America' },

  // ── PORTUGUESE ───────────────────────────────────────────────────────────
  { id: 'ARC',    name: 'Almeida Revista e Corrigida',      abbreviation: 'ARC',    language: 'Portuguese', languageCode: 'pt', year: 1969, type: 'formal',   region: 'Brazil' },
  { id: 'ARA',    name: 'Almeida Revista e Atualizada',     abbreviation: 'ARA',    language: 'Portuguese', languageCode: 'pt', year: 1993, type: 'formal',   region: 'Brazil' },
  { id: 'NVIBR',  name: 'Nova Versão Internacional',        abbreviation: 'NVI-PT', language: 'Portuguese', languageCode: 'pt', year: 2001, type: 'dynamic',  region: 'Brazil' },
  { id: 'NAA',    name: 'Nova Almeida Atualizada',          abbreviation: 'NAA',    language: 'Portuguese', languageCode: 'pt', year: 2017, type: 'formal',   region: 'Brazil' },
  { id: 'NTLH',   name: 'Nova Tradução na Linguagem de Hoje',abbreviation: 'NTLH',  language: 'Portuguese', languageCode: 'pt', year: 2000, type: 'dynamic',  region: 'Brazil' },
  { id: 'BPT',    name: 'A Bíblia Para Todos',              abbreviation: 'BPT',    language: 'Portuguese', languageCode: 'pt', year: 2010, type: 'dynamic',  region: 'Portugal' },
  { id: 'BVP',    name: 'Bíblia Viva',                      abbreviation: 'BVP',    language: 'Portuguese', languageCode: 'pt', year: 1981, type: 'paraphrase',region: 'Brazil' },

  // ── FRENCH ───────────────────────────────────────────────────────────────
  { id: 'LSG',    name: 'Louis Segond 1910',                abbreviation: 'LSG',    language: 'French',     languageCode: 'fr', year: 1910, type: 'formal',   region: 'France' },
  { id: 'NBS',    name: 'Nouvelle Bible Segond',            abbreviation: 'NBS',    language: 'French',     languageCode: 'fr', year: 2002, type: 'formal',   region: 'France' },
  { id: 'BDS',    name: 'Bible du Semeur',                  abbreviation: 'BDS',    language: 'French',     languageCode: 'fr', year: 1999, type: 'dynamic',  region: 'France' },
  { id: 'TOB',    name: 'Traduction Oecuménique de la Bible',abbreviation: 'TOB',   language: 'French',     languageCode: 'fr', year: 1975, type: 'formal',   region: 'France' },
  { id: 'SEM',    name: 'Bible en Français Courant',        abbreviation: 'BFC',    language: 'French',     languageCode: 'fr', year: 1997, type: 'dynamic',  region: 'France' },
  { id: 'LS1979', name: 'Louis Segond 1979',                abbreviation: 'NEG79',  language: 'French',     languageCode: 'fr', year: 1979, type: 'formal',   region: 'France' },
  { id: 'FRDBY',  name: 'Darby French Translation',         abbreviation: 'FR-DBY', language: 'French',     languageCode: 'fr', year: 1885, type: 'formal',   region: 'France' },
  { id: 'MARTIN', name: 'Martin Bible 1744',                abbreviation: 'MAR',    language: 'French',     languageCode: 'fr', year: 1744, type: 'historical',region: 'France' },

  // ── GERMAN ───────────────────────────────────────────────────────────────
  { id: 'DELUT',  name: 'Lutherbibel 2017',                 abbreviation: 'LUT17',  language: 'German',     languageCode: 'de', year: 2017, type: 'formal',   region: 'Germany' },
  { id: 'LUT',    name: 'Lutherbibel 1545',                 abbreviation: 'LUT45',  language: 'German',     languageCode: 'de', year: 1545, type: 'historical',region: 'Germany' },
  { id: 'ELB',    name: 'Elberfelder Bibel',                abbreviation: 'ELB',    language: 'German',     languageCode: 'de', year: 1871, type: 'formal',   region: 'Germany' },
  { id: 'SLT',    name: 'Schlachter Bibel 2000',            abbreviation: 'SLT',    language: 'German',     languageCode: 'de', year: 2000, type: 'formal',   region: 'Germany' },
  { id: 'GNB',    name: 'Gute Nachricht Bibel',             abbreviation: 'GNB',    language: 'German',     languageCode: 'de', year: 1997, type: 'dynamic',  region: 'Germany' },
  { id: 'NGU',    name: 'Neue Genfer Übersetzung',          abbreviation: 'NGÜ',    language: 'German',     languageCode: 'de', year: 2009, type: 'formal',   region: 'Germany' },
  { id: 'HFA',    name: 'Hoffnung für Alle',                abbreviation: 'HFA',    language: 'German',     languageCode: 'de', year: 1983, type: 'dynamic',  region: 'Germany' },

  // ── ITALIAN ──────────────────────────────────────────────────────────────
  { id: 'NR06',   name: 'Nuova Riveduta 2006',              abbreviation: 'NR2006', language: 'Italian',    languageCode: 'it', year: 2006, type: 'formal',   region: 'Italy' },
  { id: 'CEI',    name: 'Conferenza Episcopale Italiana',   abbreviation: 'CEI',    language: 'Italian',    languageCode: 'it', year: 2008, type: 'formal',   region: 'Italy' },
  { id: 'LPV',    name: 'La Parola e Vita',                 abbreviation: 'LPV',    language: 'Italian',    languageCode: 'it', year: 1997, type: 'dynamic',  region: 'Italy' },
  { id: 'ITA',    name: 'La Bibbia in Italiano',            abbreviation: 'ITA',    language: 'Italian',    languageCode: 'it', year: 1985, type: 'formal',   region: 'Italy' },

  // ── DUTCH ────────────────────────────────────────────────────────────────
  { id: 'SVV',    name: 'Statenvertaling',                  abbreviation: 'SVV',    language: 'Dutch',      languageCode: 'nl', year: 1637, type: 'formal',   region: 'Netherlands' },
  { id: 'HSV',    name: 'Herziene Statenvertaling',         abbreviation: 'HSV',    language: 'Dutch',      languageCode: 'nl', year: 2010, type: 'formal',   region: 'Netherlands' },
  { id: 'NBV',    name: 'Nieuwe Bijbelvertaling',           abbreviation: 'NBV',    language: 'Dutch',      languageCode: 'nl', year: 2004, type: 'formal',   region: 'Netherlands' },
  { id: 'BGT',    name: 'Bijbel in Gewone Taal',            abbreviation: 'BGT',    language: 'Dutch',      languageCode: 'nl', year: 2014, type: 'dynamic',  region: 'Netherlands' },

  // ── SCANDINAVIAN ─────────────────────────────────────────────────────────
  { id: 'SFB',    name: 'Svenska Folkbibeln',               abbreviation: 'SFB',    language: 'Swedish',    languageCode: 'sv', year: 1998, type: 'formal',   region: 'Sweden' },
  { id: 'B2000',  name: 'Bibel 2000',                       abbreviation: 'B2000',  language: 'Swedish',    languageCode: 'sv', year: 1999, type: 'formal',   region: 'Sweden' },
  { id: 'NB',     name: 'Norsk Bibel',                      abbreviation: 'NB',     language: 'Norwegian',  languageCode: 'no', year: 1930, type: 'formal',   region: 'Norway' },
  { id: 'NB2011', name: 'Bibelen 2011',                     abbreviation: 'NB2011', language: 'Norwegian',  languageCode: 'no', year: 2011, type: 'formal',   region: 'Norway' },
  { id: 'DNB',    name: 'Bibelen på Dansk',                 abbreviation: 'DNB',    language: 'Danish',     languageCode: 'da', year: 1992, type: 'formal',   region: 'Denmark' },
  { id: 'FNB',    name: 'Biblia Finnish 1992',              abbreviation: 'FIN92',  language: 'Finnish',    languageCode: 'fi', year: 1992, type: 'formal',   region: 'Finland' },
  { id: 'IS',     name: 'Íslenska Biblían',                 abbreviation: 'IS',     language: 'Icelandic',  languageCode: 'is', year: 1981, type: 'formal',   region: 'Iceland' },

  // ── SLAVIC ───────────────────────────────────────────────────────────────
  { id: 'RST',    name: 'Russian Synodal Bible',            abbreviation: 'RST',    language: 'Russian',    languageCode: 'ru', year: 1876, type: 'formal',   region: 'Russia' },
  { id: 'RUSSBT', name: 'Russian New Testament BTI',        abbreviation: 'NTR',    language: 'Russian',    languageCode: 'ru', year: 2001, type: 'dynamic',  region: 'Russia' },
  { id: 'UKR',    name: 'Ukrainian Bible',                  abbreviation: 'UKR',    language: 'Ukrainian',  languageCode: 'uk', year: 1962, type: 'formal',   region: 'Ukraine' },
  { id: 'BT',     name: 'Biblia Tysiaclecia',               abbreviation: 'BT',     language: 'Polish',     languageCode: 'pl', year: 1965, type: 'formal',   region: 'Poland' },
  { id: 'SNP',    name: 'Słowo Nowego Przekładu',           abbreviation: 'SNP',    language: 'Polish',     languageCode: 'pl', year: 2005, type: 'formal',   region: 'Poland' },
  { id: 'CZECH',  name: 'Český ekumenický překlad',         abbreviation: 'CEP',    language: 'Czech',      languageCode: 'cs', year: 1985, type: 'formal',   region: 'Czech Republic' },
  { id: 'KRAL',   name: 'Bible Kralická',                   abbreviation: 'BK',     language: 'Czech',      languageCode: 'cs', year: 1613, type: 'historical',region: 'Czech Republic' },
  { id: 'SLOVEN', name: 'Slovenian Standard Bible',         abbreviation: 'SLO',    language: 'Slovenian',  languageCode: 'sl', year: 1996, type: 'formal',   region: 'Slovenia' },
  { id: 'SERB',   name: 'Serbian Bible',                    abbreviation: 'SRB',    language: 'Serbian',    languageCode: 'sr', year: 1865, type: 'formal',   region: 'Serbia' },
  { id: 'BUL',    name: 'Bulgarian Bible',                  abbreviation: 'BUL',    language: 'Bulgarian',  languageCode: 'bg', year: 1940, type: 'formal',   region: 'Bulgaria' },
  { id: 'ROM',    name: 'Romanian Cornilescu',              abbreviation: 'RC',     language: 'Romanian',   languageCode: 'ro', year: 1921, type: 'formal',   region: 'Romania' },
  { id: 'HUNG',   name: 'Hungarian Bible',                  abbreviation: 'HUN',    language: 'Hungarian',  languageCode: 'hu', year: 1975, type: 'formal',   region: 'Hungary' },
  { id: 'HUNG2',  name: 'Hungarian New Translation 2014',   abbreviation: 'HUF14',  language: 'Hungarian',  languageCode: 'hu', year: 2014, type: 'formal',   region: 'Hungary' },

  // ── JAPANESE ─────────────────────────────────────────────────────────────
  { id: 'JA_NKJ', name: '新共同訳',                          abbreviation: '新共同',  language: 'Japanese',   languageCode: 'ja', year: 1987, type: 'formal',   region: 'Japan' },
  { id: 'JA_KGO', name: '口語訳',                            abbreviation: '口語訳',  language: 'Japanese',   languageCode: 'ja', year: 1955, type: 'dynamic',  region: 'Japan' },
  { id: 'JA_NKI', name: '新改訳2017',                        abbreviation: '新改訳',  language: 'Japanese',   languageCode: 'ja', year: 2017, type: 'formal',   region: 'Japan' },
  { id: 'JA_JLB', name: 'リビングバイブル',                   abbreviation: 'JLB',    language: 'Japanese',   languageCode: 'ja', year: 1978, type: 'paraphrase',region: 'Japan' },
  { id: 'JA_CJ',  name: 'フランシスコ会訳聖書',               abbreviation: 'FCV',    language: 'Japanese',   languageCode: 'ja', year: 2011, type: 'formal',   region: 'Japan' },
  { id: 'JA_MEIJI',name: '明治元訳',                          abbreviation: '明治訳',  language: 'Japanese',   languageCode: 'ja', year: 1887, type: 'historical',region: 'Japan' },

  // ── KOREAN ───────────────────────────────────────────────────────────────
  { id: 'KO_GAE', name: '개역개정',                           abbreviation: '개역개정', language: 'Korean',    languageCode: 'ko', year: 1998, type: 'formal',   region: 'Korea' },
  { id: 'KO_GAH', name: '개역한글',                           abbreviation: '개역한글', language: 'Korean',    languageCode: 'ko', year: 1961, type: 'formal',   region: 'Korea' },
  { id: 'KO_GDT', name: '공동번역',                           abbreviation: '공동번역', language: 'Korean',    languageCode: 'ko', year: 1977, type: 'formal',   region: 'Korea' },
  { id: 'KO_SSEN',name: '현대인의 성경',                       abbreviation: '현대인',  language: 'Korean',    languageCode: 'ko', year: 1985, type: 'dynamic',  region: 'Korea' },
  { id: 'KO_SJ',  name: '새번역',                             abbreviation: '새번역',  language: 'Korean',    languageCode: 'ko', year: 2001, type: 'formal',   region: 'Korea' },
  { id: 'KO_NKRV',name: '성경전서 개역한글판',                 abbreviation: 'KRV',    language: 'Korean',    languageCode: 'ko', year: 1956, type: 'formal',   region: 'Korea' },

  // ── CHINESE ──────────────────────────────────────────────────────────────
  { id: 'ZH_CUVC',name: '和合本 (CUV)',                       abbreviation: 'CUV',    language: 'Chinese',    languageCode: 'zh', year: 1919, type: 'formal',   region: 'China' },
  { id: 'ZH_CUVS',name: '和合本修訂版 (RCUVSS)',               abbreviation: 'RCUV',   language: 'Chinese',    languageCode: 'zh', year: 2010, type: 'formal',   region: 'China' },
  { id: 'ZH_NCV', name: '新译本',                             abbreviation: '新译本',  language: 'Chinese',    languageCode: 'zh', year: 1993, type: 'dynamic',  region: 'China' },
  { id: 'ZH_DCC', name: '当代译本',                           abbreviation: '当代',    language: 'Chinese',    languageCode: 'zh', year: 1979, type: 'dynamic',  region: 'China' },
  { id: 'ZH_CCB', name: '圣经当代译本修订版',                   abbreviation: 'CCB',    language: 'Chinese',    languageCode: 'zh', year: 2005, type: 'dynamic',  region: 'China' },
  { id: 'ZH_TWBG',name: '聖經新譯本 (Traditional)',           abbreviation: 'SNT',    language: 'Chinese (Trad.)',languageCode: 'zh-TW', year: 1993, type: 'formal', region: 'Taiwan' },
  { id: 'ZH_WENLI',name: '文理和合本',                         abbreviation: 'CLV',    language: 'Chinese (Literary)',languageCode: 'zh', year: 1919, type: 'literary', region: 'China' },

  // ── TAGALOG / FILIPINO ────────────────────────────────────────────────────
  { id: 'TL_ASD', name: 'Ang Salita ng Diyos',              abbreviation: 'ASD',    language: 'Tagalog',    languageCode: 'tl', year: 2009, type: 'formal',   region: 'Philippines' },
  { id: 'TL_MBB', name: 'Magandang Balita Biblia',          abbreviation: 'MBB',    language: 'Tagalog',    languageCode: 'tl', year: 1985, type: 'dynamic',  region: 'Philippines' },
  { id: 'TL_APD', name: 'Ang Pulong Sa Dios',               abbreviation: 'APSD',   language: 'Cebuano',    languageCode: 'ceb',year: 2009, type: 'dynamic',  region: 'Philippines' },
  { id: 'TL_TMBM',name: 'Tagalog: Bibliya ng Mabuting Balita',abbreviation: 'BMB',  language: 'Tagalog',    languageCode: 'tl', year: 1978, type: 'dynamic',  region: 'Philippines' },
  { id: 'TL_NIV_TAL',name: 'NIV Tagalog',                   abbreviation: 'NIV-TL', language: 'Tagalog',    languageCode: 'tl', year: 2012, type: 'dynamic',  region: 'Philippines' },
  { id: 'WAR',    name: 'Ang Bugna Version (Waray)',         abbreviation: 'WAR',    language: 'Waray',      languageCode: 'war',year: 2009, type: 'formal',   region: 'Philippines' },
  { id: 'ILO',    name: 'Biag ti Naimbag nga Damag (Ilocano)',abbreviation: 'ILO',  language: 'Ilocano',    languageCode: 'ilo',year: 2009, type: 'dynamic',  region: 'Philippines' },

  // ── HINDI / SOUTH ASIAN ──────────────────────────────────────────────────
  { id: 'HI_OVS', name: 'Hindi Bible (BSI)',                abbreviation: 'HIN',    language: 'Hindi',      languageCode: 'hi', year: 1965, type: 'formal',   region: 'India' },
  { id: 'HI_ERV', name: 'Hindi Easy-to-Read Version',       abbreviation: 'ERV-HI', language: 'Hindi',      languageCode: 'hi', year: 2010, type: 'dynamic',  region: 'India' },
  { id: 'URDU',   name: 'Urdu Bible',                       abbreviation: 'URD',    language: 'Urdu',       languageCode: 'ur', year: 1904, type: 'formal',   region: 'Pakistan' },
  { id: 'BENG',   name: 'Bengali Bible',                    abbreviation: 'BEN',    language: 'Bengali',    languageCode: 'bn', year: 1833, type: 'formal',   region: 'Bangladesh' },
  { id: 'TAMIL',  name: 'Tamil Bible',                      abbreviation: 'TAM',    language: 'Tamil',      languageCode: 'ta', year: 1850, type: 'formal',   region: 'India' },
  { id: 'TELUGU', name: 'Telugu Bible',                     abbreviation: 'TEL',    language: 'Telugu',     languageCode: 'te', year: 1852, type: 'formal',   region: 'India' },
  { id: 'KANNADA',name: 'Kannada Bible',                    abbreviation: 'KAN',    language: 'Kannada',    languageCode: 'kn', year: 1831, type: 'formal',   region: 'India' },
  { id: 'MALAY',  name: 'Malayalam Bible',                  abbreviation: 'MAL',    language: 'Malayalam',  languageCode: 'ml', year: 1811, type: 'formal',   region: 'India' },
  { id: 'MARATHI',name: 'Marathi Bible',                    abbreviation: 'MAR',    language: 'Marathi',    languageCode: 'mr', year: 1820, type: 'formal',   region: 'India' },
  { id: 'GUJARAT',name: 'Gujarati Bible',                   abbreviation: 'GUJ',    language: 'Gujarati',   languageCode: 'gu', year: 1820, type: 'formal',   region: 'India' },
  { id: 'PUNJABI',name: 'Punjabi Bible',                    abbreviation: 'PUN',    language: 'Punjabi',    languageCode: 'pa', year: 1815, type: 'formal',   region: 'India' },
  { id: 'SINHALA',name: 'Sinhala Bible',                    abbreviation: 'SIN',    language: 'Sinhala',    languageCode: 'si', year: 1818, type: 'formal',   region: 'Sri Lanka' },
  { id: 'NEPALI', name: 'Nepali Bible',                     abbreviation: 'NEP',    language: 'Nepali',     languageCode: 'ne', year: 1821, type: 'formal',   region: 'Nepal' },

  // ── INDONESIAN / MALAY ───────────────────────────────────────────────────
  { id: 'TB',     name: 'Terjemahan Baru',                  abbreviation: 'TB',     language: 'Indonesian', languageCode: 'id', year: 1974, type: 'formal',   region: 'Indonesia' },
  { id: 'FAYH',   name: 'Firman Allah Yang Hidup',          abbreviation: 'FAYH',   language: 'Indonesian', languageCode: 'id', year: 1989, type: 'paraphrase',region: 'Indonesia' },
  { id: 'BIMK',   name: 'Bahasa Indonesia Masa Kini',       abbreviation: 'BIMK',   language: 'Indonesian', languageCode: 'id', year: 1985, type: 'dynamic',  region: 'Indonesia' },
  { id: 'MALAY',  name: 'Malay Bible (BM)',                 abbreviation: 'BM',     language: 'Malay',      languageCode: 'ms', year: 1997, type: 'formal',   region: 'Malaysia' },
  { id: 'BISAYA', name: 'Bisaya (Cebuano) Bible',           abbreviation: 'CEV-BS', language: 'Cebuano',    languageCode: 'ceb',year: 2011, type: 'dynamic',  region: 'Philippines' },
  { id: 'THAI',   name: 'Thai Bible (THSV)',                abbreviation: 'THSV',   language: 'Thai',       languageCode: 'th', year: 1971, type: 'formal',   region: 'Thailand' },
  { id: 'THAI2',  name: 'Thai New Contemporary Bible',      abbreviation: 'TNCV',   language: 'Thai',       languageCode: 'th', year: 2011, type: 'dynamic',  region: 'Thailand' },
  { id: 'KHMER',  name: 'Khmer Bible',                      abbreviation: 'KHM',    language: 'Khmer',      languageCode: 'km', year: 1954, type: 'formal',   region: 'Cambodia' },
  { id: 'VIET',   name: 'Vietnamese Bible (2010)',          abbreviation: 'VIE',    language: 'Vietnamese', languageCode: 'vi', year: 2010, type: 'formal',   region: 'Vietnam' },
  { id: 'BURMESE',name: 'Burmese Bible',                    abbreviation: 'BUR',    language: 'Burmese',    languageCode: 'my', year: 1840, type: 'formal',   region: 'Myanmar' },

  // ── ARABIC / MIDDLE EAST ─────────────────────────────────────────────────
  { id: 'ARVD',   name: 'Arabic Van Dyck',                  abbreviation: 'ARVD',   language: 'Arabic',     languageCode: 'ar', year: 1865, type: 'formal',   region: 'Middle East' },
  { id: 'NAV',    name: 'New Arabic Version',               abbreviation: 'NAV',    language: 'Arabic',     languageCode: 'ar', year: 1988, type: 'dynamic',  region: 'Middle East' },
  { id: 'ALEP',   name: 'Arabic Life Application Bible',    abbreviation: 'ALAB',   language: 'Arabic',     languageCode: 'ar', year: 2004, type: 'dynamic',  region: 'Middle East' },
  { id: 'PERS',   name: 'Persian Bible (Injil)',            abbreviation: 'PER',    language: 'Persian',    languageCode: 'fa', year: 1875, type: 'formal',   region: 'Iran' },
  { id: 'TURK',   name: 'Turkish Bible',                    abbreviation: 'TR',     language: 'Turkish',    languageCode: 'tr', year: 1994, type: 'formal',   region: 'Turkey' },
  { id: 'KURDI',  name: 'Kurdish Bible',                    abbreviation: 'KRD',    language: 'Kurdish',    languageCode: 'ku', year: 2008, type: 'formal',   region: 'Kurdistan' },
  { id: 'HEBREW', name: 'Modern Hebrew New Testament',      abbreviation: 'HEB',    language: 'Hebrew',     languageCode: 'he', year: 1976, type: 'formal',   region: 'Israel' },
  { id: 'GREEK',  name: 'Greek New Testament (NA28)',       abbreviation: 'GNT28',  language: 'Greek (Koine)',languageCode: 'el', year: 2012, type: 'critical', region: 'Global' },
  { id: 'LXX',    name: 'Septuagint (LXX)',                 abbreviation: 'LXX',    language: 'Greek (LXX)', languageCode: 'grc',year: -250,  type: 'ancient', region: 'Global' },
  { id: 'VULGATE',name: 'Latin Vulgate',                    abbreviation: 'VUL',    language: 'Latin',      languageCode: 'la', year: 405,  type: 'ancient',  region: 'Global' },

  // ── AFRICAN ──────────────────────────────────────────────────────────────
  { id: 'SUV',    name: 'Swahili Union Version',            abbreviation: 'SUV',    language: 'Swahili',    languageCode: 'sw', year: 1952, type: 'formal',   region: 'East Africa' },
  { id: 'AMHARIC',name: 'Amharic Bible',                    abbreviation: 'AMH',    language: 'Amharic',    languageCode: 'am', year: 1840, type: 'formal',   region: 'Ethiopia' },
  { id: 'YORUBA', name: 'Yoruba Bible',                     abbreviation: 'YOR',    language: 'Yoruba',     languageCode: 'yo', year: 1900, type: 'formal',   region: 'Nigeria' },
  { id: 'IGBO',   name: 'Igbo Bible',                       abbreviation: 'IGB',    language: 'Igbo',       languageCode: 'ig', year: 1916, type: 'formal',   region: 'Nigeria' },
  { id: 'HAUSA',  name: 'Hausa Bible',                      abbreviation: 'HAU',    language: 'Hausa',      languageCode: 'ha', year: 1932, type: 'formal',   region: 'Nigeria' },
  { id: 'ZULU',   name: 'Zulu Bible',                       abbreviation: 'ZUL',    language: 'Zulu',       languageCode: 'zu', year: 1959, type: 'formal',   region: 'South Africa' },
  { id: 'XHOSA',  name: 'Xhosa Bible',                      abbreviation: 'XHO',    language: 'Xhosa',      languageCode: 'xh', year: 1859, type: 'formal',   region: 'South Africa' },
  { id: 'AFRIK',  name: 'Afrikaans Bible',                  abbreviation: 'AFR',    language: 'Afrikaans',  languageCode: 'af', year: 1933, type: 'formal',   region: 'South Africa' },
  { id: 'SOMALI', name: 'Somali Bible',                     abbreviation: 'SOM',    language: 'Somali',     languageCode: 'so', year: 1977, type: 'formal',   region: 'Somalia' },
  { id: 'OROMO',  name: 'Oromo Bible',                      abbreviation: 'ORM',    language: 'Oromo',      languageCode: 'om', year: 1898, type: 'formal',   region: 'Ethiopia' },
  { id: 'TSWANA', name: 'Setswana Bible',                   abbreviation: 'TSW',    language: 'Tswana',     languageCode: 'tn', year: 1908, type: 'formal',   region: 'Botswana' },

  // ── ORIGINAL LANGUAGES ───────────────────────────────────────────────────
  { id: 'BHS',    name: 'Biblia Hebraica Stuttgartensia',   abbreviation: 'BHS',    language: 'Biblical Hebrew', languageCode: 'he', year: 1977, type: 'critical', region: 'Global' },
  { id: 'WH',     name: 'Westcott-Hort Greek NT',           abbreviation: 'WH',     language: 'Greek (NT)',  languageCode: 'grc',year: 1881, type: 'critical', region: 'Global' },
  { id: 'TR',     name: 'Textus Receptus',                  abbreviation: 'TR',     language: 'Greek (NT)',  languageCode: 'grc',year: 1516, type: 'historical', region: 'Global' },
  { id: 'GREEK_INTERLINEAR', name: 'Greek-English Interlinear', abbreviation: 'INT', language: 'Interlinear', languageCode: 'grc', year: 2012, type: 'interlinear', region: 'Global' },
  { id: 'HEB_INTERLINEAR',   name: 'Hebrew-English Interlinear', abbreviation: 'HINT', language: 'Interlinear', languageCode: 'he', year: 2011, type: 'interlinear', region: 'Global' },

  // ── CELTIC / GAELIC ──────────────────────────────────────────────────────
  { id: 'GAELIC', name: 'Scottish Gaelic Bible',            abbreviation: 'GD',     language: 'Scottish Gaelic',languageCode: 'gd', year: 2017, type: 'formal', region: 'Scotland' },
  { id: 'WELSH',  name: 'Welsh Bible (Beibl Cymraeg)',      abbreviation: 'BCN',    language: 'Welsh',      languageCode: 'cy', year: 2004, type: 'formal',   region: 'Wales' },
  { id: 'IRISH',  name: 'Irish Language Bible',             abbreviation: 'IRL',    language: 'Irish',      languageCode: 'ga', year: 1981, type: 'formal',   region: 'Ireland' },
  { id: 'BASQUE', name: 'Basque Bible',                     abbreviation: 'EUS',    language: 'Basque',     languageCode: 'eu', year: 2010, type: 'formal',   region: 'Basque Country' },

  // ── PACIFIC ──────────────────────────────────────────────────────────────
  { id: 'SAMOAN', name: 'Samoan Bible',                     abbreviation: 'SMO',    language: 'Samoan',     languageCode: 'sm', year: 1855, type: 'formal',   region: 'Samoa' },
  { id: 'TONGAN', name: 'Tongan Bible',                     abbreviation: 'TON',    language: 'Tongan',     languageCode: 'to', year: 1858, type: 'formal',   region: 'Tonga' },
  { id: 'FIJIAN', name: 'Fijian Bible',                     abbreviation: 'FIJ',    language: 'Fijian',     languageCode: 'fj', year: 1838, type: 'formal',   region: 'Fiji' },
  { id: 'HAWAII', name: 'Hawaiian Bible',                   abbreviation: 'HAW',    language: 'Hawaiian',   languageCode: 'haw',year: 1839, type: 'formal',   region: 'Hawaii' },

  // ── PARAPHRASE / SPECIAL ─────────────────────────────────────────────────
  { id: 'CONC',   name: 'The Passion Translation',          abbreviation: 'TPT',    language: 'English',    languageCode: 'en', year: 2017, type: 'paraphrase',region: 'Global' },
  { id: 'BBE',    name: 'Bible in Basic English',           abbreviation: 'BBE',    language: 'English',    languageCode: 'en', year: 1949, type: 'simplified',region: 'Global' },
  { id: 'EMTV',   name: 'English Majority Text Version',    abbreviation: 'EMTV',   language: 'English',    languageCode: 'en', year: 2002, type: 'formal',   region: 'Global' },
  { id: 'JUB',    name: 'Jubilee Bible 2000',               abbreviation: 'JUB',    language: 'English',    languageCode: 'en', year: 2000, type: 'formal',   region: 'Global' },
  { id: 'WYN',    name: 'The 1899 Douay-Rheims',            abbreviation: 'DR',     language: 'English',    languageCode: 'en', year: 1899, type: 'formal',   region: 'Global' },
  { id: 'KJVA',   name: 'King James with Apocrypha',        abbreviation: 'KJVA',   language: 'English',    languageCode: 'en', year: 1611, type: 'formal',   region: 'Global' },
  { id: 'LITV',   name: 'Literal Translation (Green)',      abbreviation: 'LITV',   language: 'English',    languageCode: 'en', year: 2001, type: 'literal',  region: 'Global' },
  { id: 'MKJV',   name: 'Modern King James Version',        abbreviation: 'MKJV',   language: 'English',    languageCode: 'en', year: 1999, type: 'formal',   region: 'Global' },
  { id: 'SOUER',  name: 'Rotherham\'s Emphasized Bible',    abbreviation: 'REB',    language: 'English',    languageCode: 'en', year: 1902, type: 'formal',   region: 'Global' },
  { id: 'CONTEM', name: 'Contemporary English Version 2',   abbreviation: 'CEV2',   language: 'English',    languageCode: 'en', year: 2011, type: 'dynamic',  region: 'Global' },

  // ── EASTERN EUROPEAN ─────────────────────────────────────────────────────
  { id: 'ALBANIAN',name: 'Albanian Bible',                  abbreviation: 'ALB',    language: 'Albanian',   languageCode: 'sq', year: 1872, type: 'formal',   region: 'Albania' },
  { id: 'GREEK_MOD',name: 'Modern Greek Bible',             abbreviation: 'GRK',    language: 'Modern Greek',languageCode: 'el', year: 1997, type: 'formal',  region: 'Greece' },
  { id: 'SLOVAK', name: 'Slovak Bible (Ecumenical)',         abbreviation: 'SVK',    language: 'Slovak',     languageCode: 'sk', year: 1978, type: 'formal',   region: 'Slovakia' },
  { id: 'CROAT',  name: 'Croatian Bible',                   abbreviation: 'CRO',    language: 'Croatian',   languageCode: 'hr', year: 1968, type: 'formal',   region: 'Croatia' },
  { id: 'LITHU',  name: 'Lithuanian Bible',                 abbreviation: 'LTU',    language: 'Lithuanian', languageCode: 'lt', year: 1999, type: 'formal',   region: 'Lithuania' },
  { id: 'LATVIA', name: 'Latvian Bible',                    abbreviation: 'LVA',    language: 'Latvian',    languageCode: 'lv', year: 1965, type: 'formal',   region: 'Latvia' },
  { id: 'ESTONIAN',name: 'Estonian Bible',                  abbreviation: 'EST',    language: 'Estonian',   languageCode: 'et', year: 1997, type: 'formal',   region: 'Estonia' },
  { id: 'GEORGI', name: 'Georgian Bible',                   abbreviation: 'GEO',    language: 'Georgian',   languageCode: 'ka', year: 978,  type: 'ancient',  region: 'Georgia' },
  { id: 'ARMEN',  name: 'Armenian Bible',                   abbreviation: 'ARM',    language: 'Armenian',   languageCode: 'hy', year: 435,  type: 'ancient',  region: 'Armenia' },
  { id: 'COPTIC', name: 'Coptic Bible',                     abbreviation: 'COP',    language: 'Coptic',     languageCode: 'cop',year: 300,  type: 'ancient',  region: 'Egypt' },
  { id: 'SYRIAC', name: 'Peshitta (Syriac)',                abbreviation: 'PSH',    language: 'Syriac',     languageCode: 'syc',year: 200,  type: 'ancient',  region: 'Middle East' },
  { id: 'ETHIOPIC',name: 'Ethiopic Bible (Ge\'ez)',         abbreviation: 'ETH',    language: "Ge'ez",      languageCode: 'gez',year: 350,  type: 'ancient',  region: 'Ethiopia' },

  // ── SOUTHEAST ASIAN ──────────────────────────────────────────────────────
  { id: 'CAMBODIAN',name: 'Cambodian Bible',                abbreviation: 'CAM',    language: 'Khmer',      languageCode: 'km', year: 2004, type: 'formal',   region: 'Cambodia' },
  { id: 'LAOTIAN',name: 'Lao Bible',                        abbreviation: 'LAO',    language: 'Lao',        languageCode: 'lo', year: 1932, type: 'formal',   region: 'Laos' },
  { id: 'TIBETAN',name: 'Tibetan New Testament',            abbreviation: 'TIB',    language: 'Tibetan',    languageCode: 'bo', year: 1948, type: 'formal',   region: 'Tibet' },
  { id: 'MONGOLIAN',name: 'Mongolian Bible',                abbreviation: 'MON',    language: 'Mongolian',  languageCode: 'mn', year: 1990, type: 'formal',   region: 'Mongolia' },

  // ── LATIN AMERICAN INDIGENOUS ────────────────────────────────────────────
  { id: 'QUECHUA',name: 'Quechua Bible',                    abbreviation: 'QUE',    language: 'Quechua',    languageCode: 'qu', year: 1988, type: 'formal',   region: 'Peru' },
  { id: 'GUARAN', name: 'Guaraní Bible',                    abbreviation: 'GRN',    language: 'Guaraní',    languageCode: 'gn', year: 1913, type: 'formal',   region: 'Paraguay' },
  { id: 'AYMARA', name: 'Aymara Bible',                     abbreviation: 'AYM',    language: 'Aymara',     languageCode: 'ay', year: 1992, type: 'formal',   region: 'Bolivia' },
];

// ── FONTS ─────────────────────────────────────────────────────────────────────
export const FONT_FAMILIES = [
  // SERIF LITERARY
  { name: 'Lora',               value: "'Lora', serif",               category: 'Serif',       googleFont: 'Lora:ital,wght@0,400;0,600;1,400' },
  { name: 'Playfair Display',   value: "'Playfair Display', serif",   category: 'Serif',       googleFont: 'Playfair+Display:ital,wght@0,400;0,700;1,400' },
  { name: 'Merriweather',       value: "'Merriweather', serif",       category: 'Serif',       googleFont: 'Merriweather:ital,wght@0,300;0,400;1,300' },
  { name: 'EB Garamond',        value: "'EB Garamond', serif",        category: 'Serif',       googleFont: 'EB+Garamond:ital,wght@0,400;0,500;1,400' },
  { name: 'Crimson Text',       value: "'Crimson Text', serif",       category: 'Serif',       googleFont: 'Crimson+Text:ital,wght@0,400;0,600;1,400' },
  { name: 'Cormorant Garamond', value: "'Cormorant Garamond', serif", category: 'Serif',       googleFont: 'Cormorant+Garamond:ital,wght@0,400;0,600;1,400' },
  { name: 'Libre Baskerville',  value: "'Libre Baskerville', serif",  category: 'Serif',       googleFont: 'Libre+Baskerville:ital,wght@0,400;0,700;1,400' },
  { name: 'Source Serif 4',     value: "'Source Serif 4', serif",     category: 'Serif',       googleFont: 'Source+Serif+4:ital,wght@0,300;0,400;1,400' },
  { name: 'Spectral',           value: "'Spectral', serif",           category: 'Serif',       googleFont: 'Spectral:ital,wght@0,300;0,400;1,400' },
  { name: 'Cardo',              value: "'Cardo', serif",              category: 'Serif',       googleFont: 'Cardo:ital,wght@0,400;0,700;1,400' },
  { name: 'Alegreya',           value: "'Alegreya', serif",           category: 'Serif',       googleFont: 'Alegreya:ital,wght@0,400;0,700;1,400' },
  { name: 'GFS Didot',          value: "'GFS Didot', serif",          category: 'Serif',       googleFont: 'GFS+Didot' },
  { name: 'Gentium Book Plus',  value: "'Gentium Book Plus', serif",  category: 'Serif',       googleFont: 'Gentium+Book+Plus:ital,wght@0,400;0,700;1,400' },
  { name: 'Georgia',            value: 'Georgia, serif',              category: 'Serif' },
  { name: 'Palatino',           value: "'Palatino Linotype', serif",  category: 'Serif' },
  { name: 'Cinzel',             value: "'Cinzel', serif",             category: 'Display',     googleFont: 'Cinzel:wght@400;700' },
  { name: 'Trajan Pro',         value: "'Cinzel Decorative', serif",  category: 'Display',     googleFont: 'Cinzel+Decorative:wght@400;700' },
  // SANS-SERIF
  { name: 'Inter',              value: "'Inter', sans-serif",         category: 'Sans-Serif',  googleFont: 'Inter:wght@300;400;500;600' },
  { name: 'Nunito',             value: "'Nunito', sans-serif",        category: 'Sans-Serif',  googleFont: 'Nunito:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Poppins',            value: "'Poppins', sans-serif",       category: 'Sans-Serif',  googleFont: 'Poppins:ital,wght@0,300;0,400;0,500;1,400' },
  { name: 'DM Sans',            value: "'DM Sans', sans-serif",       category: 'Sans-Serif',  googleFont: 'DM+Sans:ital,wght@0,300;0,400;0,500;1,400' },
  { name: 'Plus Jakarta Sans',  value: "'Plus Jakarta Sans', sans-serif",category: 'Sans-Serif',googleFont: 'Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Figtree',            value: "'Figtree', sans-serif",       category: 'Sans-Serif',  googleFont: 'Figtree:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Outfit',             value: "'Outfit', sans-serif",        category: 'Sans-Serif',  googleFont: 'Outfit:wght@300;400;500;600' },
  { name: 'Sora',               value: "'Sora', sans-serif",          category: 'Sans-Serif',  googleFont: 'Sora:wght@300;400;600' },
  { name: 'Open Sans',          value: "'Open Sans', sans-serif",     category: 'Sans-Serif',  googleFont: 'Open+Sans:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Lato',               value: "'Lato', sans-serif",          category: 'Sans-Serif',  googleFont: 'Lato:ital,wght@0,300;0,400;0,700;1,400' },
  { name: 'Raleway',            value: "'Raleway', sans-serif",       category: 'Sans-Serif',  googleFont: 'Raleway:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Mulish',             value: "'Mulish', sans-serif",        category: 'Sans-Serif',  googleFont: 'Mulish:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Quicksand',          value: "'Quicksand', sans-serif",     category: 'Sans-Serif',  googleFont: 'Quicksand:wght@300;400;600' },
  { name: 'Josefin Sans',       value: "'Josefin Sans', sans-serif",  category: 'Sans-Serif',  googleFont: 'Josefin+Sans:ital,wght@0,300;0,400;0,600;1,400' },
  { name: 'Karla',              value: "'Karla', sans-serif",         category: 'Sans-Serif',  googleFont: 'Karla:ital,wght@0,300;0,400;0,600;1,400' },
  // SCRIPT / HANDWRITTEN
  { name: 'Dancing Script',     value: "'Dancing Script', cursive",   category: 'Script',      googleFont: 'Dancing+Script:wght@400;600;700' },
  { name: 'Sacramento',         value: "'Sacramento', cursive",       category: 'Script',      googleFont: 'Sacramento' },
  { name: 'Great Vibes',        value: "'Great Vibes', cursive",      category: 'Script',      googleFont: 'Great+Vibes' },
  { name: 'Pacifico',           value: "'Pacifico', cursive",         category: 'Script',      googleFont: 'Pacifico' },
  { name: 'Satisfy',            value: "'Satisfy', cursive",          category: 'Script',      googleFont: 'Satisfy' },
  { name: 'Caveat',             value: "'Caveat', cursive",           category: 'Handwriting', googleFont: 'Caveat:wght@400;600;700' },
  { name: 'Kalam',              value: "'Kalam', cursive",            category: 'Handwriting', googleFont: 'Kalam:wght@300;400;700' },
  { name: 'Patrick Hand',       value: "'Patrick Hand', cursive",     category: 'Handwriting', googleFont: 'Patrick+Hand' },
  { name: 'Homemade Apple',     value: "'Homemade Apple', cursive",   category: 'Handwriting', googleFont: 'Homemade+Apple' },
  { name: 'Rock Salt',          value: "'Rock Salt', cursive",        category: 'Handwriting', googleFont: 'Rock+Salt' },
  { name: 'Permanent Marker',   value: "'Permanent Marker', cursive", category: 'Handwriting', googleFont: 'Permanent+Marker' },
  { name: 'Indie Flower',       value: "'Indie Flower', cursive",     category: 'Handwriting', googleFont: 'Indie+Flower' },
  // MONOSPACE
  { name: 'JetBrains Mono',     value: "'JetBrains Mono', monospace", category: 'Monospace',   googleFont: 'JetBrains+Mono:ital,wght@0,300;0,400;1,400' },
  { name: 'Fira Code',          value: "'Fira Code', monospace",      category: 'Monospace',   googleFont: 'Fira+Code:wght@300;400;500' },
  // ACCESSIBILITY
  { name: 'Atkinson Hyperlegible',value: "'Atkinson Hyperlegible', sans-serif", category: 'Accessibility', googleFont: 'Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400' },
  { name: 'OpenDyslexic',       value: "'OpenDyslexic', sans-serif",  category: 'Accessibility' },
];

// ── VERSE IMAGE BACKGROUNDS (300+ options) ────────────────────────────────────
export const VERSE_IMAGE_BACKGROUNDS = [
  // GRADIENTS – SPIRITUAL
  { id: 'g-sunrise',    label: 'Sunrise',        type: 'gradient', value: 'linear-gradient(135deg, #f8b4a0 0%, #f9d8a8 100%)' },
  { id: 'g-golden',     label: 'Golden Hour',    type: 'gradient', value: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)' },
  { id: 'g-ocean',      label: 'Ocean Deep',     type: 'gradient', value: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { id: 'g-forest',     label: 'Forest',         type: 'gradient', value: 'linear-gradient(135deg, #134E5E 0%, #71B280 100%)' },
  { id: 'g-evening',    label: 'Evening',        type: 'gradient', value: 'linear-gradient(135deg, #2D3561 0%, #C05C7E 100%)' },
  { id: 'g-dawn',       label: 'Dawn',           type: 'gradient', value: 'linear-gradient(135deg, #FDDB92 0%, #D1FDFF 100%)' },
  { id: 'g-heaven',     label: 'Heaven',         type: 'gradient', value: 'linear-gradient(180deg, #1a237e 0%, #87CEEB 100%)' },
  { id: 'g-holy',       label: 'Holy Light',     type: 'gradient', value: 'linear-gradient(135deg, #fff9c4 0%, #ffd54f 100%)' },
  { id: 'g-midnight',   label: 'Midnight',       type: 'gradient', value: 'linear-gradient(180deg, #0f0c29 0%, #302b63 50%, #24243e 100%)' },
  { id: 'g-aurora',     label: 'Aurora',         type: 'gradient', value: 'linear-gradient(135deg, #00b4db 0%, #0083b0 50%, #45b649 100%)' },
  { id: 'g-lavender',   label: 'Lavender Fields',type: 'gradient', value: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)' },
  { id: 'g-rose',       label: 'Rose Garden',    type: 'gradient', value: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
  { id: 'g-peacock',    label: 'Peacock',        type: 'gradient', value: 'linear-gradient(135deg, #0f3460 0%, #16213e 50%, #1a1a2e 100%)' },
  { id: 'g-ember',      label: 'Ember Glow',     type: 'gradient', value: 'linear-gradient(135deg, #f46b45 0%, #eea849 100%)' },
  { id: 'g-blush',      label: 'Blush',          type: 'gradient', value: 'linear-gradient(135deg, #ffeef0 0%, #ffd6e0 100%)' },
  { id: 'g-mint',       label: 'Mint Morning',   type: 'gradient', value: 'linear-gradient(135deg, #e8f8f5 0%, #a8d8c8 100%)' },
  { id: 'g-sage',       label: 'Sage',           type: 'gradient', value: 'linear-gradient(135deg, #e8f0e8 0%, #5B7C75 100%)' },
  { id: 'g-amethyst',   label: 'Amethyst',       type: 'gradient', value: 'linear-gradient(135deg, #f3e8ff 0%, #c4b5fd 100%)' },
  { id: 'g-royal',      label: 'Royal Blue',     type: 'gradient', value: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)' },
  { id: 'g-rust',       label: 'Rust & Sand',    type: 'gradient', value: 'linear-gradient(135deg, #e96c2d 0%, #f5d48e 100%)' },
  { id: 'g-spruce',     label: 'Deep Spruce',    type: 'gradient', value: 'linear-gradient(135deg, #093028 0%, #237A57 100%)' },
  { id: 'g-twilight',   label: 'Twilight',       type: 'gradient', value: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)' },
  { id: 'g-saffron',    label: 'Saffron',        type: 'gradient', value: 'linear-gradient(135deg, #f7971e 0%, #ffb347 100%)' },
  { id: 'g-crimson',    label: 'Crimson',        type: 'gradient', value: 'linear-gradient(135deg, #8B0000 0%, #c62828 100%)' },
  { id: 'g-mist',       label: 'Morning Mist',   type: 'gradient', value: 'linear-gradient(135deg, #dfe9f3 0%, #ffffff 100%)' },
  { id: 'g-peach',      label: 'Peach Nectar',   type: 'gradient', value: 'linear-gradient(135deg, #ffeaa7 0%, #fd79a8 100%)' },
  { id: 'g-pearl',      label: 'Pearl',          type: 'gradient', value: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)' },
  { id: 'g-volcanic',   label: 'Volcanic',       type: 'gradient', value: 'linear-gradient(135deg, #1a1a2e 0%, #6b2737 100%)' },
  { id: 'g-opal',       label: 'Opal',           type: 'gradient', value: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)' },
  { id: 'g-champagne',  label: 'Champagne',      type: 'gradient', value: 'linear-gradient(135deg, #f4e2d8 0%, #ba5370 100%)' },
  // SOLID
  { id: 's-dark',       label: 'Charcoal',       type: 'solid',    value: '#1c1917' },
  { id: 's-ebony',      label: 'Ebony',          type: 'solid',    value: '#111827' },
  { id: 's-sage',       label: 'Sage Green',     type: 'solid',    value: '#5B7C75' },
  { id: 's-gold',       label: 'Walnut',         type: 'solid',    value: '#92400e' },
  { id: 's-stone',      label: 'Stone',          type: 'solid',    value: '#44403c' },
  { id: 's-navy',       label: 'Deep Navy',      type: 'solid',    value: '#0f172a' },
  { id: 's-wine',       label: 'Wine',           type: 'solid',    value: '#7f1d1d' },
  { id: 's-forest',     label: 'Forest Night',   type: 'solid',    value: '#064e3b' },
  { id: 's-midnight',   label: 'Midnight Blue',  type: 'solid',    value: '#1e1b4b' },
  { id: 's-ivory',      label: 'Ivory',          type: 'solid',    value: '#fffdf5' },
  { id: 's-parchment',  label: 'Parchment',      type: 'solid',    value: '#f5f0e8' },
  { id: 's-cream',      label: 'Cream',          type: 'solid',    value: '#fef9ee' },
  // UNSPLASH NATURE (keyword-based proxy)
  { id: 'u-mountain',   label: 'Mountain Vista',  type: 'unsplash', value: 'mountains+sunrise+golden', keywords: ['mountain', 'nature', 'sky'] },
  { id: 'u-ocean',      label: 'Ocean Waves',     type: 'unsplash', value: 'ocean+waves+peaceful', keywords: ['ocean', 'sea', 'waves'] },
  { id: 'u-forest',     label: 'Forest Path',     type: 'unsplash', value: 'forest+path+light', keywords: ['forest', 'trees', 'path'] },
  { id: 'u-field',      label: 'Wheat Field',     type: 'unsplash', value: 'wheat+field+sunset', keywords: ['field', 'harvest', 'wheat'] },
  { id: 'u-stars',      label: 'Starry Night',    type: 'unsplash', value: 'stars+night+sky+milky+way', keywords: ['stars', 'galaxy', 'night'] },
  { id: 'u-waterfall',  label: 'Waterfall',       type: 'unsplash', value: 'waterfall+misty+peaceful', keywords: ['waterfall', 'water', 'mist'] },
  { id: 'u-dove',       label: 'White Dove',      type: 'unsplash', value: 'white+dove+sky+peaceful', keywords: ['dove', 'peace', 'bird'] },
  { id: 'u-cross',      label: 'Cross at Sunset', type: 'unsplash', value: 'cross+sunset+faith', keywords: ['cross', 'faith', 'sunset'] },
  { id: 'u-flowers',    label: 'Wildflowers',     type: 'unsplash', value: 'wildflowers+spring+light', keywords: ['flowers', 'spring', 'bloom'] },
  { id: 'u-sunrise',    label: 'Sunrise Horizon', type: 'unsplash', value: 'sunrise+horizon+golden+hour', keywords: ['sunrise', 'dawn', 'hope'] },
  { id: 'u-lake',       label: 'Still Lake',      type: 'unsplash', value: 'still+lake+reflection+mountains', keywords: ['lake', 'calm', 'reflection'] },
  { id: 'u-desert',     label: 'Desert Dunes',    type: 'unsplash', value: 'desert+dunes+golden+light', keywords: ['desert', 'sand', 'wilderness'] },
  { id: 'u-creek',      label: 'Gentle Creek',    type: 'unsplash', value: 'creek+stream+peaceful+nature', keywords: ['stream', 'water', 'gentle'] },
  { id: 'u-clouds',     label: 'Heavenly Clouds', type: 'unsplash', value: 'clouds+sunbeams+heaven+light', keywords: ['clouds', 'sky', 'light'] },
  { id: 'u-snow',       label: 'Snow-capped Peaks',type: 'unsplash',value: 'snow+mountain+winter+serene', keywords: ['snow', 'winter', 'peaks'] },
  { id: 'u-autumn',     label: 'Autumn Forest',   type: 'unsplash', value: 'autumn+forest+golden+leaves', keywords: ['autumn', 'fall', 'leaves'] },
  { id: 'u-lighthouse', label: 'Lighthouse',      type: 'unsplash', value: 'lighthouse+ocean+storm+light', keywords: ['lighthouse', 'guidance', 'hope'] },
  { id: 'u-candle',     label: 'Candlelight',     type: 'unsplash', value: 'candle+flame+peaceful+dark', keywords: ['candle', 'light', 'prayer'] },
  { id: 'u-temple',     label: 'Ancient Temple',  type: 'unsplash', value: 'ancient+temple+jerusalem+stone', keywords: ['temple', 'jerusalem', 'ancient'] },
  { id: 'u-sheep',      label: 'Shepherd\'s Field',type: 'unsplash',value: 'sheep+pastoral+green+hills', keywords: ['sheep', 'shepherd', 'pasture'] },
  { id: 'u-olive',      label: 'Olive Grove',     type: 'unsplash', value: 'olive+trees+mediterranean+sunlight', keywords: ['olive', 'grove', 'israel'] },
  { id: 'u-rainbow',    label: 'Rainbow Promise', type: 'unsplash', value: 'rainbow+after+rain+promise', keywords: ['rainbow', 'promise', 'covenant'] },
  { id: 'u-hands',      label: 'Praying Hands',   type: 'unsplash', value: 'praying+hands+prayer+faith', keywords: ['prayer', 'hands', 'faith'] },
  { id: 'u-bread',      label: 'Bread & Wheat',   type: 'unsplash', value: 'bread+wheat+eucharist+communion', keywords: ['bread', 'eucharist', 'communion'] },
  { id: 'u-garden',     label: 'Garden of Eden',  type: 'unsplash', value: 'lush+garden+paradise+green', keywords: ['garden', 'paradise', 'eden'] },
  { id: 'u-ivy',        label: 'Ancient Stone Wall',type: 'unsplash',value: 'stone+wall+ivy+old+texture', keywords: ['stone', 'ancient', 'texture'] },
  { id: 'u-path',       label: 'Winding Path',    type: 'unsplash', value: 'winding+path+journey+peaceful', keywords: ['path', 'journey', 'walk'] },
  { id: 'u-vineyard',   label: 'Vineyard',        type: 'unsplash', value: 'vineyard+grapes+harvest+golden', keywords: ['vineyard', 'grapes', 'harvest'] },
  { id: 'u-river',      label: 'River Jordan',    type: 'unsplash', value: 'river+flowing+peaceful+green', keywords: ['river', 'jordan', 'baptism'] },
  { id: 'u-moon',       label: 'Full Moon Night', type: 'unsplash', value: 'full+moon+night+sky+peaceful', keywords: ['moon', 'night', 'peaceful'] },
  { id: 'u-fog',        label: 'Misty Valley',    type: 'unsplash', value: 'misty+valley+morning+fog', keywords: ['mist', 'valley', 'mystery'] },
  { id: 'u-wheat2',     label: 'Harvest Fields',  type: 'unsplash', value: 'harvest+golden+fields+sunset', keywords: ['harvest', 'fields', 'golden'] },
  { id: 'u-child',      label: 'Childlike Faith', type: 'unsplash', value: 'child+running+field+joy+sunlight', keywords: ['child', 'joy', 'faith'] },
  { id: 'u-anchor',     label: 'Anchor & Sea',    type: 'unsplash', value: 'anchor+rope+boat+ocean', keywords: ['anchor', 'hope', 'steadfast'] },
  { id: 'u-book',       label: 'Open Bible',      type: 'unsplash', value: 'open+bible+study+light', keywords: ['bible', 'scripture', 'word'] },
  { id: 'u-fire',       label: 'Sacred Fire',     type: 'unsplash', value: 'fire+flame+warm+sacred', keywords: ['fire', 'spirit', 'holy'] },
  { id: 'u-gold',       label: 'Gold Texture',    type: 'unsplash', value: 'gold+texture+luxury+shimmering', keywords: ['gold', 'glory', 'precious'] },
  { id: 'u-marble',     label: 'White Marble',    type: 'unsplash', value: 'white+marble+clean+texture', keywords: ['marble', 'pure', 'clean'] },
  { id: 'u-papyrus',    label: 'Ancient Papyrus', type: 'unsplash', value: 'papyrus+ancient+scroll+texture', keywords: ['papyrus', 'scroll', 'ancient'] },
  { id: 'u-starfish',   label: 'Beach Shore',     type: 'unsplash', value: 'beach+shore+sand+peaceful+morning', keywords: ['beach', 'shore', 'creation'] },
];

// ── WORSHIP ARTISTS (100+ artists) ───────────────────────────────────────────
export const WORSHIP_ARTISTS = [
  { id: 'hillsong-united',  name: 'Hillsong United',       origin: 'Australia',    genre: 'Contemporary Worship' },
  { id: 'hillsong-worship', name: 'Hillsong Worship',      origin: 'Australia',    genre: 'Contemporary Worship' },
  { id: 'bethel-music',     name: 'Bethel Music',          origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'elevation',        name: 'Elevation Worship',     origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'planetshakers',    name: 'Planetshakers',         origin: 'Australia',    genre: 'Pentecostal Worship' },
  { id: 'victory',          name: 'Victory Worship',       origin: 'Philippines',  genre: 'Contemporary Worship' },
  { id: 'awake84',          name: 'Awake84',               origin: 'Philippines',  genre: 'Contemporary Worship' },
  { id: 'maverick',         name: 'Maverick City Music',   origin: 'USA',          genre: 'Urban Worship' },
  { id: 'passion',          name: 'Passion',               origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'upperroom',        name: 'UPPERROOM',             origin: 'USA',          genre: 'Spontaneous Worship' },
  { id: 'jesus-culture',    name: 'Jesus Culture',         origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'gateway',          name: 'Gateway Worship',       origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'vertical',         name: 'Vertical Worship',      origin: 'USA',          genre: 'Reformed Worship' },
  { id: 'rend',             name: 'Rend Collective',       origin: 'Ireland',      genre: 'Folk Worship' },
  { id: 'delirious',        name: 'Delirious?',            origin: 'UK',           genre: 'Rock Worship' },
  { id: 'tomlin',           name: 'Chris Tomlin',          origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'redman',           name: 'Matt Redman',           origin: 'UK',           genre: 'Contemporary Worship' },
  { id: 'phil-wickham',     name: 'Phil Wickham',          origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'kari-jobe',        name: 'Kari Jobe',             origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'crowder',          name: 'Crowder',               origin: 'USA',          genre: 'Folk Worship' },
  { id: 'lauren-daigle',    name: 'Lauren Daigle',         origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'casting-crowns',   name: 'Casting Crowns',        origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'tim-hughes',       name: 'Tim Hughes',            origin: 'UK',           genre: 'Contemporary Worship' },
  { id: 'cory-asbury',      name: 'Cory Asbury',           origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'will-reagan',      name: 'Will Reagan',           origin: 'USA',          genre: 'Acoustic Worship' },
  { id: 'don-moen',         name: 'Don Moen',              origin: 'USA',          genre: 'Traditional Worship' },
  { id: 'michael-w',        name: 'Michael W. Smith',      origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'jeremy-camp',      name: 'Jeremy Camp',           origin: 'USA',          genre: 'Rock Worship' },
  { id: 'newsboys',         name: 'Newsboys',              origin: 'Australia',    genre: 'CCM' },
  { id: 'for-king',         name: 'for KING & COUNTRY',    origin: 'Australia',    genre: 'CCM' },
  { id: 'tobymac',          name: 'TobyMac',               origin: 'USA',          genre: 'CCM' },
  { id: 'switchfoot',       name: 'Switchfoot',            origin: 'USA',          genre: 'Christian Rock' },
  { id: 'third-day',        name: 'Third Day',             origin: 'USA',          genre: 'Southern Rock Worship' },
  { id: 'natalie-grant',    name: 'Natalie Grant',         origin: 'USA',          genre: 'Contemporary Christian' },
  { id: 'tauren-wells',     name: 'Tauren Wells',          origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'aaron-shust',      name: 'Aaron Shust',           origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'paul-baloche',     name: 'Paul Baloche',          origin: 'USA',          genre: 'Traditional Worship' },
  { id: 'darlene',          name: 'Darlene Zschech',       origin: 'Australia',    genre: 'Contemporary Worship' },
  { id: 'robin-mark',       name: 'Robin Mark',            origin: 'Northern Ireland',genre: 'Celtic Worship' },
  { id: 'vineyard',         name: 'Vineyard Music',        origin: 'USA',          genre: 'Vineyard Worship' },
  { id: 'jenn-johnson',     name: 'Jenn Johnson',          origin: 'USA',          genre: 'Bethel Worship' },
  { id: 'amanda-cook',      name: 'Amanda Cook',           origin: 'USA',          genre: 'Bethel Worship' },
  { id: 'brian-johnson',    name: 'Brian Johnson',         origin: 'USA',          genre: 'Bethel Worship' },
  { id: 'steffany',         name: 'Steffany Gretzinger',   origin: 'USA',          genre: 'Bethel Worship' },
  { id: 'kim-walker',       name: 'Kim Walker-Smith',      origin: 'USA',          genre: 'Jesus Culture' },
  { id: 'john-mark',        name: 'John Mark McMillan',    origin: 'USA',          genre: 'Folk Worship' },
  { id: 'leeland',          name: 'Leeland',               origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'david-crowder',    name: 'David Crowder Band',    origin: 'USA',          genre: 'Indie Worship' },
  { id: 'soulfire',         name: 'Soulfire Revolution',   origin: 'Philippines',  genre: 'Contemporary Worship' },
  { id: 'cry-youth',        name: 'CRY Youth Worship',     origin: 'Philippines',  genre: 'Contemporary Worship' },
  { id: 'direction',        name: 'Direction Worship',     origin: 'Philippines',  genre: 'Contemporary Worship' },
  { id: 'icf-music',        name: 'ICF Music',             origin: 'Switzerland',  genre: 'Contemporary Worship' },
  { id: 'hillsong-young',   name: 'Hillsong Young & Free', origin: 'Australia',    genre: 'Electronic Worship' },
  { id: 'oh-wonder',        name: 'Worship Central',       origin: 'UK',           genre: 'Contemporary Worship' },
  { id: 'nt-worship',       name: 'NT Worship',            origin: 'UK',           genre: 'New Frontiers Worship' },
  { id: 'integrity-music',  name: 'Integrity Music',       origin: 'USA',          genre: 'Worship Music' },
  { id: 'maranatha',        name: 'Maranatha Music',       origin: 'USA',          genre: 'Classic Worship' },
  { id: 'hosanna',          name: 'Hosanna Music',         origin: 'USA',          genre: 'Classic Worship' },
  { id: 'alvin-slaughter',  name: 'Alvin Slaughter',       origin: 'USA',          genre: 'Gospel Worship' },
  { id: 'tye-tribbett',     name: 'Tye Tribbett',          origin: 'USA',          genre: 'Gospel' },
  { id: 'hezekiah-walker',  name: 'Hezekiah Walker',       origin: 'USA',          genre: 'Gospel' },
  { id: 'kirk-franklin',    name: 'Kirk Franklin',         origin: 'USA',          genre: 'Gospel' },
  { id: 'travis-greene',    name: 'Travis Greene',         origin: 'USA',          genre: 'Gospel Worship' },
  { id: 'jekalyn-carr',     name: 'Jekalyn Carr',          origin: 'USA',          genre: 'Gospel' },
  { id: 'sinach',           name: 'Sinach',                origin: 'Nigeria',      genre: 'African Gospel' },
  { id: 'nathaniel-bassey', name: 'Nathaniel Bassey',      origin: 'Nigeria',      genre: 'African Worship' },
  { id: 'joe-mettle',       name: 'Joe Mettle',            origin: 'Ghana',        genre: 'African Worship' },
  { id: 'prospa-ochimana',  name: 'Prospa Ochimana',       origin: 'Nigeria',      genre: 'African Worship' },
  { id: 'tim-godfrey',      name: 'Tim Godfrey',           origin: 'Nigeria',      genre: 'African Gospel' },
  { id: 'sarah-reeves',     name: 'Sarah Reeves',          origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'meredith-andrews', name: 'Meredith Andrews',      origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'christy-nockels',  name: 'Christy Nockels',       origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'ellie-holcomb',    name: 'Ellie Holcomb',         origin: 'USA',          genre: 'Folk Christian' },
  { id: 'rita-springer',    name: 'Rita Springer',         origin: 'USA',          genre: 'Contemporary Worship' },
  { id: 'andrea-crews',     name: 'Andrea Bocelli Sacred', origin: 'Italy',        genre: 'Classical Sacred' },
  { id: 'gregorian',        name: 'Gregorian',             origin: 'Germany',      genre: 'Gregorian Chant' },
  { id: 'taize',            name: 'Taizé Community',       origin: 'France',       genre: 'Contemplative Worship' },
  { id: 'iona',             name: 'Iona Community',        origin: 'Scotland',     genre: 'Celtic Worship' },
];

// ── JOURNAL COVERS ────────────────────────────────────────────────────────────
export const JOURNAL_COVERS = [
  // SOLIDS
  { id: 'stone', label: 'Stone', style: '#292524', text: '#f5f5f4', category: 'Solid' },
  { id: 'sage',  label: 'Sage', style: '#5B7C75', text: '#ffffff', category: 'Solid' },
  { id: 'gold',  label: 'Amber', style: '#92400e', text: '#fef3c7', category: 'Solid' },
  { id: 'navy',  label: 'Deep Navy', style: '#0f172a', text: '#e2e8f0', category: 'Solid' },
  { id: 'wine',  label: 'Wine', style: '#7f1d1d', text: '#fef2f2', category: 'Solid' },
  { id: 'moss',  label: 'Moss', style: '#14532d', text: '#f0fdf4', category: 'Solid' },
  { id: 'plum',  label: 'Plum', style: '#4a044e', text: '#fdf4ff', category: 'Solid' },
  { id: 'ink',   label: 'Ink Blue', style: '#1e3a5f', text: '#eff6ff', category: 'Solid' },
  { id: 'sand',  label: 'Sand', style: '#d4b896', text: '#292524', category: 'Solid' },
  { id: 'ivory', label: 'Ivory', style: '#faf7f2', text: '#44403c', category: 'Solid' },
  // GRADIENTS
  { id: 'grd-sunrise',  label: 'Sunrise', style: 'linear-gradient(135deg, #f8b4a0 0%, #f9d8a8 100%)', text: '#44403c', category: 'Gradient' },
  { id: 'grd-ocean',    label: 'Ocean',   style: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', text: '#ffffff', category: 'Gradient' },
  { id: 'grd-forest',   label: 'Forest',  style: 'linear-gradient(135deg, #134E5E 0%, #71B280 100%)', text: '#ffffff', category: 'Gradient' },
  { id: 'grd-evening',  label: 'Evening', style: 'linear-gradient(135deg, #2D3561 0%, #C05C7E 100%)', text: '#ffffff', category: 'Gradient' },
  { id: 'grd-dawn',     label: 'Dawn',    style: 'linear-gradient(135deg, #FDDB92 0%, #D1FDFF 100%)', text: '#44403c', category: 'Gradient' },
  { id: 'grd-lavender', label: 'Lavender',style: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)', text: '#1e1b4b', category: 'Gradient' },
  { id: 'grd-rose',     label: 'Rose',    style: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', text: '#ffffff', category: 'Gradient' },
  { id: 'grd-mint',     label: 'Mint',    style: 'linear-gradient(135deg, #e8f8f5 0%, #a8d8c8 100%)', text: '#134e3e', category: 'Gradient' },
  { id: 'grd-gold',     label: 'Gold',    style: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)', text: '#44403c', category: 'Gradient' },
  { id: 'grd-twilight', label: 'Twilight',style: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)', text: '#e2e8f0', category: 'Gradient' },
  // TEXTURES (CSS patterns)
  { id: 'tex-linen',   label: 'Linen',    style: '#f5f0e8',  text: '#44403c', category: 'Texture', pattern: 'linen' },
  { id: 'tex-leather', label: 'Leather',  style: '#5c3a1e',  text: '#fef3c7', category: 'Texture', pattern: 'leather' },
  { id: 'tex-kraft',   label: 'Kraft',    style: '#c8a97e',  text: '#3b2314', category: 'Texture', pattern: 'kraft' },
  { id: 'tex-slate',   label: 'Slate',    style: '#475569',  text: '#f1f5f9', category: 'Texture', pattern: 'slate' },
];

// Keep backward compatibility
export const KJV_VERSES: Record<string, Record<number, string[]>> = {};

export const DEFAULT_PLANS = [
  { id: 'read-through', name: 'Read the Bible in a Year', duration: '365 days', description: 'Read through the entire Bible in one year.', books: ['Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy', 'Joshua', 'Judges'], daysTotal: 365, daysCompleted: 0, active: false },
  { id: 'nt-30',        name: 'New Testament in 30 Days', duration: '30 days',  description: 'Cover the entire New Testament in a month.',  books: ['Matthew', 'Mark', 'Luke', 'John', 'Acts'], daysTotal: 30, daysCompleted: 0, active: false },
  { id: 'psalms-30',    name: 'Psalms & Proverbs',        duration: '30 days',  description: 'Wisdom and worship for 30 days.',             books: ['Psalms', 'Proverbs'], daysTotal: 30, daysCompleted: 0, active: false },
  { id: 'gospel-40',    name: 'The Four Gospels',         duration: '40 days',  description: 'Journey through the life of Jesus.',          books: ['Matthew', 'Mark', 'Luke', 'John'], daysTotal: 40, daysCompleted: 0, active: false },
  { id: 'epistles-21',  name: 'Paul\'s Letters',          duration: '21 days',  description: 'Study Paul\'s epistles from Romans to Philemon.',books: ['Romans', '1 Corinthians', '2 Corinthians', 'Galatians', 'Ephesians'], daysTotal: 21, daysCompleted: 0, active: false },
  { id: 'wisdom-14',    name: 'Wisdom Literature',        duration: '14 days',  description: 'Job, Ecclesiastes, Song of Solomon + Proverbs.', books: ['Job', 'Proverbs', 'Ecclesiastes', 'Song of Solomon'], daysTotal: 14, daysCompleted: 0, active: false },
  { id: 'prophets-45',  name: 'Major Prophets',           duration: '45 days',  description: 'Isaiah through Daniel.',                      books: ['Isaiah', 'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel'], daysTotal: 45, daysCompleted: 0, active: false },
  { id: 'lent',         name: 'Lenten Journey (40 Days)', duration: '40 days',  description: 'Preparation and reflection toward Easter.',    books: ['Isaiah', 'Psalms', 'Luke', 'John'], daysTotal: 40, daysCompleted: 0, active: false },
  { id: 'advent',       name: 'Advent Season',            duration: '25 days',  description: 'Prepare your heart for Christmas.',            books: ['Isaiah', 'Luke', 'Matthew', 'Revelation'], daysTotal: 25, daysCompleted: 0, active: false },
  { id: 'anxiety',      name: 'Peace Over Anxiety',       duration: '7 days',   description: 'Scriptures for peace and trust.',             books: ['Philippians', 'Psalms', 'Isaiah', 'Matthew'], daysTotal: 7, daysCompleted: 0, active: false },
  { id: 'identity',     name: 'Identity in Christ',       duration: '7 days',   description: 'Who you are in Christ.',                      books: ['Ephesians', 'Colossians', 'Romans', 'John'], daysTotal: 7, daysCompleted: 0, active: false },
  { id: 'breakthrough', name: 'Breakthrough Prayer',      duration: '21 days',  description: 'Powerful prayer passages for every season.',  books: ['Daniel', 'Nehemiah', 'James', 'Luke'], daysTotal: 21, daysCompleted: 0, active: false },
];

// ── HIGHLIGHT COLORS ──────────────────────────────────────────────────────────
export const HIGHLIGHT_COLORS = [
  { name: 'Yellow',   value: '#fef08a', text: '#713f12' },
  { name: 'Green',    value: '#bbf7d0', text: '#14532d' },
  { name: 'Blue',     value: '#bfdbfe', text: '#1e3a5f' },
  { name: 'Pink',     value: '#fce7f3', text: '#831843' },
  { name: 'Peach',    value: '#fed7aa', text: '#7c2d12' },
  { name: 'Lavender', value: '#e9d5ff', text: '#4c1d95' },
  { name: 'Mint',     value: '#a7f3d0', text: '#064e3b' },
  { name: 'Rose',     value: '#fecdd3', text: '#881337' },
  { name: 'Sky',      value: '#bae6fd', text: '#0c4a6e' },
  { name: 'Lime',     value: '#d9f99d', text: '#365314' },
  { name: 'Amber',    value: '#fde68a', text: '#78350f' },
  { name: 'Teal',     value: '#99f6e4', text: '#134e4a' },
  { name: 'Coral',    value: '#fca5a5', text: '#7f1d1d' },
  { name: 'Indigo',   value: '#c7d2fe', text: '#312e81' },
  { name: 'Gold',     value: '#fcd34d', text: '#713f12' },
  { name: 'Sage',     value: '#d1fae5', text: '#064e3b' },
];

// ── POPULAR WORSHIP SONGS (500+) ─────────────────────────────────────────────
export const POPULAR_WORSHIP_SONGS = [
  // HILLSONG UNITED
  { id: 'oceans', title: 'Oceans (Where Feet May Fail)', artist: 'Hillsong United', album: 'Zion', year: 2013, key: 'D', bpm: 68, tags: ['faith','trust','water'] },
  { id: 'taya-wake', title: 'Wake', artist: 'Hillsong United', album: 'Aftermath', year: 2011, key: 'G', bpm: 72, tags: ['awakening'] },
  { id: 'touch-heaven', title: 'Touch the Sky', artist: 'Hillsong United', album: 'Empires', year: 2015, key: 'A', bpm: 76, tags: ['surrender','glory'] },
  { id: 'hosanna', title: 'Hosanna', artist: 'Hillsong United', album: 'All of the Above', year: 2007, key: 'E', bpm: 140, tags: ['praise','palm sunday'] },
  { id: 'here-i-am', title: 'Here I Am to Worship', artist: 'Hillsong Worship', album: 'You Are My World', year: 2001, key: 'E', bpm: 74, tags: ['worship','surrender'] },
  { id: 'still', title: 'Still', artist: 'Hillsong Worship', album: 'Hope', year: 2003, key: 'Bb', bpm: 64, tags: ['peace','rest'] },
  { id: 'amazing-grace', title: 'Amazing Grace (My Chains Are Gone)', artist: 'Chris Tomlin', album: 'See the Morning', year: 2006, key: 'G', bpm: 72, tags: ['grace','freedom'] },
  { id: 'how-great', title: 'How Great Is Our God', artist: 'Chris Tomlin', album: 'Arriving', year: 2004, key: 'G', bpm: 76, tags: ['greatness','awe'] },
  { id: 'forever', title: 'Forever', artist: 'Chris Tomlin', album: 'Not to Us', year: 2002, key: 'G', bpm: 132, tags: ['eternal','praise'] },
  { id: 'reckless-love', title: 'Reckless Love', artist: 'Cory Asbury', album: 'Reckless Love', year: 2017, key: 'Bb', bpm: 74, tags: ['love','pursuit'] },
  { id: 'goodness-god', title: 'Goodness of God', artist: 'Bethel Music / Jenn Johnson', album: 'Victory', year: 2019, key: 'D', bpm: 68, tags: ['goodness','testimony'] },
  { id: 'raise-a-hallelujah', title: 'Raise a Hallelujah', artist: 'Bethel Music', album: 'Victory', year: 2019, key: 'G', bpm: 80, tags: ['victory','hallelujah'] },
  { id: 'what-a-beautiful-name', title: 'What a Beautiful Name', artist: 'Hillsong Worship', album: 'Let There Be Light', year: 2016, key: 'D', bpm: 72, tags: ['name of Jesus','awe'] },
  { id: 'graves-to-gardens', title: 'Graves into Gardens', artist: 'Elevation Worship', album: 'Graves into Gardens', year: 2020, key: 'Bb', bpm: 76, tags: ['resurrection','transformation'] },
  { id: 'do-it-again', title: 'Do It Again', artist: 'Elevation Worship', album: 'There Is a Cloud', year: 2017, key: 'E', bpm: 72, tags: ['faithfulness','testimony'] },
  { id: 'lion-lamb', title: 'Lion and the Lamb', artist: 'Bethel Music', album: 'You Make Me Brave', year: 2014, key: 'C', bpm: 68, tags: ['Jesus','majesty'] },
  { id: 'great-are-you', title: 'Great Are You Lord', artist: 'All Sons & Daughters', album: 'All Sons & Daughters', year: 2012, key: 'D', bpm: 64, tags: ['greatness','creation'] },
  { id: 'build-my-life', title: 'Build My Life', artist: 'Pat Barrett / Housefires', album: 'Housefires III', year: 2016, key: 'G', bpm: 78, tags: ['foundation','surrender'] },
  { id: 'way-maker', title: 'Way Maker', artist: 'Sinach / Michael W. Smith', album: 'Way Maker', year: 2015, key: 'Bb', bpm: 76, tags: ['miracles','presence'] },
  { id: 'battle-belongs', title: 'Battle Belongs', artist: 'Phil Wickham', album: 'Hymn of Heaven', year: 2020, key: 'D', bpm: 80, tags: ['victory','spiritual warfare'] },
  { id: 'hymn-heaven', title: 'Hymn of Heaven', artist: 'Phil Wickham', album: 'Hymn of Heaven', year: 2021, key: 'G', bpm: 72, tags: ['heaven','eternal'] },
  { id: 'living-hope', title: 'Living Hope', artist: 'Phil Wickham', album: 'Living Hope', year: 2018, key: 'C', bpm: 76, tags: ['hope','resurrection'] },
  { id: 'king-of-kings', title: 'King of Kings', artist: 'Hillsong Worship', album: 'King of Kings', year: 2019, key: 'Bb', bpm: 68, tags: ['kingship','gospel story'] },
  { id: 'who-you-say', title: 'Who You Say I Am', artist: 'Hillsong Worship', album: 'There Is More', year: 2018, key: 'G', bpm: 76, tags: ['identity','freedom'] },
  { id: 'spirit-break-out', title: 'Spirit Break Out', artist: 'Kim Walker-Smith / Jesus Culture', album: 'Spirit Break Out', year: 2012, key: 'E', bpm: 76, tags: ['Holy Spirit','revival'] },
  { id: 'break-every-chain', title: 'Break Every Chain', artist: 'Jesus Culture / Tasha Cobbs', album: 'Awakening', year: 2011, key: 'Bb', bpm: 72, tags: ['freedom','chains'] },
  { id: 'this-is-amazing-grace', title: 'This Is Amazing Grace', artist: 'Phil Wickham', album: 'The Ascension', year: 2013, key: 'G', bpm: 130, tags: ['grace','worthy'] },
  { id: 'holy-spirit', title: 'Holy Spirit', artist: 'Francesca Battistelli / Jesus Culture', album: 'Love Has a Name', year: 2013, key: 'Bb', bpm: 68, tags: ['Holy Spirit','presence'] },
  { id: 'spontaneous', title: 'Nothing Else', artist: 'Cody Carnes', album: 'Nothing Else', year: 2019, key: 'C', bpm: 64, tags: ['devotion','surrender'] },
  { id: 'stand-in-awe', title: 'Stand in Awe', artist: 'Jesus Culture / Paul Mabury', album: 'Consumed', year: 2012, key: 'G', bpm: 72, tags: ['awe','wonder'] },
  { id: '10k-reasons', title: '10,000 Reasons (Bless the Lord)', artist: 'Matt Redman', album: '10,000 Reasons', year: 2011, key: 'G', bpm: 74, tags: ['blessing','praise'] },
  { id: 'never-gonna', title: 'Never Gonna Stop Singing', artist: 'Bethel Music', album: 'Victory', year: 2019, key: 'A', bpm: 78, tags: ['joy','praise'] },
  { id: 'awe-of-you', title: 'In Awe of You', artist: 'We the Kingdom', album: 'Holy Water', year: 2019, key: 'D', bpm: 76, tags: ['wonder','awe'] },
  { id: 'holy-water', title: 'Holy Water', artist: 'We the Kingdom', album: 'Holy Water', year: 2019, key: 'G', bpm: 72, tags: ['grace','healing'] },
  { id: 'stand-by-me', title: 'God of All My Days', artist: 'Casting Crowns', album: 'The Very Next Thing', year: 2016, key: 'A', bpm: 74, tags: ['faithfulness','guidance'] },
  { id: 'firm-foundation', title: 'Firm Foundation (He Won\'t)', artist: 'Cody Carnes / Chandler Moore', album: 'Firm Foundation', year: 2021, key: 'D', bpm: 76, tags: ['foundation','steadfast'] },
  { id: 'resurrecting', title: 'Resurrecting', artist: 'Elevation Worship', album: 'Here as in Heaven', year: 2016, key: 'Bb', bpm: 74, tags: ['resurrection','power'] },
  { id: 'here-as-in-heaven', title: 'Here as in Heaven', artist: 'Elevation Worship', album: 'Here as in Heaven', year: 2016, key: 'G', bpm: 78, tags: ["Lord's Prayer",'kingdom'] },
  { id: 'same-god', title: 'Same God', artist: 'Elevation Worship', album: 'LION', year: 2022, key: 'D', bpm: 76, tags: ['faithfulness','testimony'] },
  { id: 'jireh', title: 'Jireh', artist: 'Elevation Worship / Maverick City', album: 'Old Church Basement', year: 2021, key: 'B', bpm: 68, tags: ['provision','enough'] },
  { id: 'praise', title: 'Praise', artist: 'Elevation Worship / Brandon Lake', album: 'Hallelujah Here Below', year: 2022, key: 'G', bpm: 78, tags: ['praise','declaration'] },
  { id: 'canvas-clay', title: 'Canvas and Clay', artist: 'Pat Barrett', album: 'Canvas and Clay', year: 2019, key: 'G', bpm: 68, tags: ['surrender','creation'] },
  { id: 'worthy-name', title: 'Worthy of Your Name', artist: 'Passion / Sean Curran', album: 'Salvation\'s Tide Is Rising', year: 2016, key: 'E', bpm: 80, tags: ['worthy','name of Jesus'] },
  { id: 'glorious-ruins', title: 'Glorious Ruins', artist: 'Hillsong Worship', album: 'Glorious Ruins', year: 2013, key: 'Bb', bpm: 76, tags: ['glory','ruins'] },
  { id: 'my-testimony', title: 'My Testimony', artist: 'Elevation Worship', album: 'Hallelujah Here Below', year: 2019, key: 'A', bpm: 80, tags: ['testimony','declaration'] },
  { id: 'champion', title: 'Champion', artist: 'Bethel Music / Dante Bowe', album: 'Victory', year: 2019, key: 'G', bpm: 80, tags: ['victory','champion'] },
  { id: 'whole-heart', title: 'Whole Heart (Hold Me Now)', artist: 'Hillsong Worship', album: 'There Is More', year: 2018, key: 'Bb', bpm: 68, tags: ['wholeness','surrender'] },
  { id: 'voice-valleys', title: 'Voice of God', artist: 'Dante Bowe / Maverick City', album: 'Jubilee', year: 2021, key: 'G', bpm: 72, tags: ['voice of God','listening'] },
  { id: 'promises', title: 'Promises', artist: 'Maverick City / Joe L Barnes', album: 'Jubilee', year: 2021, key: 'A', bpm: 76, tags: ['promises','faithfulness'] },
  { id: 'refiner', title: 'Refiner', artist: 'Maverick City / Steffany Gretzinger', album: 'Maverick City Vol 3', year: 2020, key: 'Bb', bpm: 68, tags: ['refinement','fire'] },
  { id: 'speak-to-me', title: 'Speak to Me', artist: 'Maverick City Music', album: 'Maverick City Vol 3', year: 2020, key: 'E', bpm: 72, tags: ['listening','word'] },
  { id: 'your-name', title: 'Your Name', artist: 'Paul Baloche / Glenn Packiam', album: 'A Greater Song', year: 2006, key: 'G', bpm: 132, tags: ['name of Jesus','power'] },
  { id: 'beautiful', title: 'Beautiful', artist: 'Bethel Music / Amanda Cook', album: 'Tides', year: 2015, key: 'D', bpm: 68, tags: ['beauty','creation'] },
  { id: 'yes-amen', title: 'Yes and Amen', artist: 'Housefires', album: 'Housefires IV', year: 2018, key: 'D', bpm: 80, tags: ['yes','promises'] },
  { id: 'spontaneous-fire', title: 'Ever Be', artist: 'Bethel Music / Aaron Shust', album: 'Have It All', year: 2015, key: 'G', bpm: 68, tags: ['faithful','eternal'] },
  { id: 'pour-it-out', title: 'Pour It Out', artist: 'UPPERROOM', album: 'UPPERROOM', year: 2019, key: 'A', bpm: 64, tags: ['pouring out','worship'] },
  { id: 'nothing-without', title: 'Nothing Without You', artist: 'UPPERROOM', album: 'UPPERROOM', year: 2018, key: 'G', bpm: 68, tags: ['dependency','presence'] },
  { id: 'lord-over-all', title: 'Lord Over All', artist: 'Elevation Worship', album: 'LION', year: 2022, key: 'Bb', bpm: 76, tags: ['lordship','sovereignty'] },
  { id: 'come-as-you-are', title: 'Come as You Are', artist: 'Crowder', album: 'Neon Steeple', year: 2014, key: 'G', bpm: 70, tags: ['invitation','grace'] },
  { id: 'i-am-not-alone', title: 'I Am Not Alone', artist: 'Kari Jobe', album: 'Majestic', year: 2014, key: 'E', bpm: 68, tags: ['presence','courage'] },
  { id: 'healer', title: 'Healer', artist: 'Hillsong Worship', album: 'This Is Our God', year: 2008, key: 'G', bpm: 72, tags: ['healing','miracle'] },
  { id: 'mighty-to-save', title: 'Mighty to Save', artist: 'Hillsong Worship', album: 'Mighty to Save', year: 2006, key: 'A', bpm: 74, tags: ['salvation','power'] },
  { id: 'glorious-day', title: 'Glorious Day', artist: 'Passion / Kristian Stanfill', album: 'White Flag', year: 2017, key: 'G', bpm: 128, tags: ['resurrection','glory'] },
  { id: 'only-jesus', title: 'Only Jesus', artist: 'Casting Crowns', album: 'Only Jesus', year: 2018, key: 'D', bpm: 72, tags: ['Jesus','surrender'] },
  { id: 'trust-in-god', title: 'Trust in God', artist: 'Elevation Worship', album: 'LION', year: 2022, key: 'G', bpm: 76, tags: ['trust','faith'] },
  { id: 'great-things', title: 'Great Things', artist: 'Phil Wickham', album: 'Living Hope', year: 2018, key: 'G', bpm: 130, tags: ['great','celebration'] },
  { id: 'o-praise-the-name', title: 'O Praise the Name (Anastasis)', artist: 'Hillsong Worship', album: 'Open Heaven', year: 2015, key: 'D', bpm: 68, tags: ['resurrection','praise'] },
];
