import { DevotionalContent, AppSettings } from './types';

export const FALLBACK_DEVOTIONAL: DevotionalContent = {
  title: "The Steady Walk",
  scripture: {
    text: "For we walk by faith, not by sight.",
    reference: "2 Corinthians 5:7"
  },
  reflection: "Our journey with Christ is often less about the destination and more about the daily rhythm of trust. Each step we take in faith draws us closer to His heart, and closer to the people He has placed in our path. Walking by faith means trusting God even when the way ahead is unclear, knowing that His plans are perfect and His timing is sure. Like a child trusting their parent's hand in the dark, we lean into God's character, not our circumstances.",
  prayer: "Lord, help me to walk by faith today. When I cannot see the path ahead, remind me that You hold my future. Guide my steps, quiet my fears, and let my life be a testimony of Your faithfulness. In Jesus name, Amen.",
  stepOfFaith: "Take a 10-minute prayer walk today, asking God to guide your steps.",
  tags: ["faith", "trust", "daily walk", "courage"]
};

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'light',
  fontSize: 18,
  fontFamily: 'Lora',
  defaultBibleVersion: 'KJV',
  language: 'en',
  animationsEnabled: true,
  footstepAnimation: true,
  showVerseNumbers: true,
  dyslexiaFriendly: false,
  highContrast: false,
  largeText: false,
};

export const CLAUDE_API_KEY = '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';

export const BIBLE_BOOKS_FULL = [
  { name: 'Genesis', category: 'Law', chapters: 50, testament: 'OT', abbr: 'Gen' },
  { name: 'Exodus', category: 'Law', chapters: 40, testament: 'OT', abbr: 'Exo' },
  { name: 'Leviticus', category: 'Law', chapters: 27, testament: 'OT', abbr: 'Lev' },
  { name: 'Numbers', category: 'Law', chapters: 36, testament: 'OT', abbr: 'Num' },
  { name: 'Deuteronomy', category: 'Law', chapters: 34, testament: 'OT', abbr: 'Deu' },
  { name: 'Joshua', category: 'History', chapters: 24, testament: 'OT', abbr: 'Jos' },
  { name: 'Judges', category: 'History', chapters: 21, testament: 'OT', abbr: 'Jdg' },
  { name: 'Ruth', category: 'History', chapters: 4, testament: 'OT', abbr: 'Rut' },
  { name: '1 Samuel', category: 'History', chapters: 31, testament: 'OT', abbr: '1Sa' },
  { name: '2 Samuel', category: 'History', chapters: 24, testament: 'OT', abbr: '2Sa' },
  { name: '1 Kings', category: 'History', chapters: 22, testament: 'OT', abbr: '1Ki' },
  { name: '2 Kings', category: 'History', chapters: 25, testament: 'OT', abbr: '2Ki' },
  { name: '1 Chronicles', category: 'History', chapters: 29, testament: 'OT', abbr: '1Ch' },
  { name: '2 Chronicles', category: 'History', chapters: 36, testament: 'OT', abbr: '2Ch' },
  { name: 'Ezra', category: 'History', chapters: 10, testament: 'OT', abbr: 'Ezr' },
  { name: 'Nehemiah', category: 'History', chapters: 13, testament: 'OT', abbr: 'Neh' },
  { name: 'Esther', category: 'History', chapters: 10, testament: 'OT', abbr: 'Est' },
  { name: 'Job', category: 'Poetry', chapters: 42, testament: 'OT', abbr: 'Job' },
  { name: 'Psalms', category: 'Poetry', chapters: 150, testament: 'OT', abbr: 'Psa' },
  { name: 'Proverbs', category: 'Poetry', chapters: 31, testament: 'OT', abbr: 'Pro' },
  { name: 'Ecclesiastes', category: 'Poetry', chapters: 12, testament: 'OT', abbr: 'Ecc' },
  { name: 'Song of Solomon', category: 'Poetry', chapters: 8, testament: 'OT', abbr: 'Son' },
  { name: 'Isaiah', category: 'Major Prophets', chapters: 66, testament: 'OT', abbr: 'Isa' },
  { name: 'Jeremiah', category: 'Major Prophets', chapters: 52, testament: 'OT', abbr: 'Jer' },
  { name: 'Lamentations', category: 'Major Prophets', chapters: 5, testament: 'OT', abbr: 'Lam' },
  { name: 'Ezekiel', category: 'Major Prophets', chapters: 48, testament: 'OT', abbr: 'Eze' },
  { name: 'Daniel', category: 'Major Prophets', chapters: 12, testament: 'OT', abbr: 'Dan' },
  { name: 'Hosea', category: 'Minor Prophets', chapters: 14, testament: 'OT', abbr: 'Hos' },
  { name: 'Joel', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Joe' },
  { name: 'Amos', category: 'Minor Prophets', chapters: 9, testament: 'OT', abbr: 'Amo' },
  { name: 'Obadiah', category: 'Minor Prophets', chapters: 1, testament: 'OT', abbr: 'Oba' },
  { name: 'Jonah', category: 'Minor Prophets', chapters: 4, testament: 'OT', abbr: 'Jon' },
  { name: 'Micah', category: 'Minor Prophets', chapters: 7, testament: 'OT', abbr: 'Mic' },
  { name: 'Nahum', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Nah' },
  { name: 'Habakkuk', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Hab' },
  { name: 'Zephaniah', category: 'Minor Prophets', chapters: 3, testament: 'OT', abbr: 'Zep' },
  { name: 'Haggai', category: 'Minor Prophets', chapters: 2, testament: 'OT', abbr: 'Hag' },
  { name: 'Zechariah', category: 'Minor Prophets', chapters: 14, testament: 'OT', abbr: 'Zec' },
  { name: 'Malachi', category: 'Minor Prophets', chapters: 4, testament: 'OT', abbr: 'Mal' },
  { name: 'Matthew', category: 'Gospels', chapters: 28, testament: 'NT', abbr: 'Mat' },
  { name: 'Mark', category: 'Gospels', chapters: 16, testament: 'NT', abbr: 'Mar' },
  { name: 'Luke', category: 'Gospels', chapters: 24, testament: 'NT', abbr: 'Luk' },
  { name: 'John', category: 'Gospels', chapters: 21, testament: 'NT', abbr: 'Joh' },
  { name: 'Acts', category: 'Acts', chapters: 28, testament: 'NT', abbr: 'Act' },
  { name: 'Romans', category: 'Epistles', chapters: 16, testament: 'NT', abbr: 'Rom' },
  { name: '1 Corinthians', category: 'Epistles', chapters: 16, testament: 'NT', abbr: '1Co' },
  { name: '2 Corinthians', category: 'Epistles', chapters: 13, testament: 'NT', abbr: '2Co' },
  { name: 'Galatians', category: 'Epistles', chapters: 6, testament: 'NT', abbr: 'Gal' },
  { name: 'Ephesians', category: 'Epistles', chapters: 6, testament: 'NT', abbr: 'Eph' },
  { name: 'Philippians', category: 'Epistles', chapters: 4, testament: 'NT', abbr: 'Phi' },
  { name: 'Colossians', category: 'Epistles', chapters: 4, testament: 'NT', abbr: 'Col' },
  { name: '1 Thessalonians', category: 'Epistles', chapters: 5, testament: 'NT', abbr: '1Th' },
  { name: '2 Thessalonians', category: 'Epistles', chapters: 3, testament: 'NT', abbr: '2Th' },
  { name: '1 Timothy', category: 'Epistles', chapters: 6, testament: 'NT', abbr: '1Ti' },
  { name: '2 Timothy', category: 'Epistles', chapters: 4, testament: 'NT', abbr: '2Ti' },
  { name: 'Titus', category: 'Epistles', chapters: 3, testament: 'NT', abbr: 'Tit' },
  { name: 'Philemon', category: 'Epistles', chapters: 1, testament: 'NT', abbr: 'Phm' },
  { name: 'Hebrews', category: 'General Epistles', chapters: 13, testament: 'NT', abbr: 'Heb' },
  { name: 'James', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: 'Jam' },
  { name: '1 Peter', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: '1Pe' },
  { name: '2 Peter', category: 'General Epistles', chapters: 3, testament: 'NT', abbr: '2Pe' },
  { name: '1 John', category: 'General Epistles', chapters: 5, testament: 'NT', abbr: '1Jo' },
  { name: '2 John', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: '2Jo' },
  { name: '3 John', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: '3Jo' },
  { name: 'Jude', category: 'General Epistles', chapters: 1, testament: 'NT', abbr: 'Jud' },
  { name: 'Revelation', category: 'Revelation', chapters: 22, testament: 'NT', abbr: 'Rev' },
];

export const COMPREHENSIVE_BIBLE_VERSIONS = [
  // ENGLISH
  { id: 'KJV', name: 'King James Version', abbreviation: 'KJV', language: 'English', languageCode: 'en', year: 1611, type: 'formal', region: 'Global' },
  { id: 'NKJV', name: 'New King James Version', abbreviation: 'NKJV', language: 'English', languageCode: 'en', year: 1982, type: 'formal', region: 'Global' },
  { id: 'ESV', name: 'English Standard Version', abbreviation: 'ESV', language: 'English', languageCode: 'en', year: 2001, type: 'formal', region: 'Global' },
  { id: 'NIV', name: 'New International Version', abbreviation: 'NIV', language: 'English', languageCode: 'en', year: 1978, type: 'dynamic', region: 'Global' },
  { id: 'NLT', name: 'New Living Translation', abbreviation: 'NLT', language: 'English', languageCode: 'en', year: 1996, type: 'dynamic', region: 'Global' },
  { id: 'NASB', name: 'New American Standard Bible', abbreviation: 'NASB', language: 'English', languageCode: 'en', year: 1971, type: 'formal', region: 'Global' },
  { id: 'NASB2020', name: 'New American Standard Bible 2020', abbreviation: 'NASB2020', language: 'English', languageCode: 'en', year: 2020, type: 'formal', region: 'Global' },
  { id: 'CSB', name: 'Christian Standard Bible', abbreviation: 'CSB', language: 'English', languageCode: 'en', year: 2017, type: 'dynamic', region: 'Global' },
  { id: 'HCSB', name: 'Holman Christian Standard Bible', abbreviation: 'HCSB', language: 'English', languageCode: 'en', year: 2004, type: 'dynamic', region: 'Global' },
  { id: 'RSV', name: 'Revised Standard Version', abbreviation: 'RSV', language: 'English', languageCode: 'en', year: 1952, type: 'formal', region: 'Global' },
  { id: 'NRSV', name: 'New Revised Standard Version', abbreviation: 'NRSV', language: 'English', languageCode: 'en', year: 1989, type: 'formal', region: 'Global' },
  { id: 'NRSVue', name: 'New Revised Standard Version Updated Edition', abbreviation: 'NRSVue', language: 'English', languageCode: 'en', year: 2021, type: 'formal', region: 'Global' },
  { id: 'MSG', name: 'The Message', abbreviation: 'MSG', language: 'English', languageCode: 'en', year: 2002, type: 'paraphrase', region: 'Global' },
  { id: 'AMP', name: 'Amplified Bible', abbreviation: 'AMP', language: 'English', languageCode: 'en', year: 1965, type: 'dynamic', region: 'Global' },
  { id: 'CEV', name: 'Contemporary English Version', abbreviation: 'CEV', language: 'English', languageCode: 'en', year: 1991, type: 'dynamic', region: 'Global' },
  { id: 'GNT', name: 'Good News Translation', abbreviation: 'GNT', language: 'English', languageCode: 'en', year: 1976, type: 'dynamic', region: 'Global' },
  { id: 'WEB', name: 'World English Bible', abbreviation: 'WEB', language: 'English', languageCode: 'en', year: 2000, type: 'formal', region: 'Global' },
  { id: 'LEB', name: 'Lexham English Bible', abbreviation: 'LEB', language: 'English', languageCode: 'en', year: 2010, type: 'literal', region: 'Global' },
  { id: 'YLT', name: "Young's Literal Translation", abbreviation: 'YLT', language: 'English', languageCode: 'en', year: 1898, type: 'literal', region: 'Global' },
  { id: 'DBY', name: "Darby's Translation", abbreviation: 'DBY', language: 'English', languageCode: 'en', year: 1890, type: 'formal', region: 'Global' },
  { id: 'ASV', name: 'American Standard Version', abbreviation: 'ASV', language: 'English', languageCode: 'en', year: 1901, type: 'formal', region: 'Global' },
  { id: 'GENEVA', name: 'Geneva Bible', abbreviation: 'GENEVA', language: 'English', languageCode: 'en', year: 1560, type: 'formal', region: 'Global' },
  { id: 'COVERDALE', name: 'Coverdale Bible', abbreviation: 'COVERDALE', language: 'English', languageCode: 'en', year: 1535, type: 'formal', region: 'Global' },
  { id: 'DOUAY', name: 'Douay-Rheims Bible', abbreviation: 'DOUAY', language: 'English', languageCode: 'en', year: 1582, type: 'formal', region: 'Global' },
  { id: 'NCV', name: 'New Century Version', abbreviation: 'NCV', language: 'English', languageCode: 'en', year: 1987, type: 'dynamic', region: 'Global' },
  { id: 'VOICE', name: 'The Voice', abbreviation: 'VOICE', language: 'English', languageCode: 'en', year: 2012, type: 'paraphrase', region: 'Global' },
  { id: 'TLB', name: 'The Living Bible', abbreviation: 'TLB', language: 'English', languageCode: 'en', year: 1971, type: 'paraphrase', region: 'Global' },
  { id: 'ERV', name: 'Easy-to-Read Version', abbreviation: 'ERV', language: 'English', languageCode: 'en', year: 1978, type: 'dynamic', region: 'Global' },
  { id: 'EXB', name: 'Expanded Bible', abbreviation: 'EXB', language: 'English', languageCode: 'en', year: 2011, type: 'dynamic', region: 'Global' },
  { id: 'PHILLIPS', name: 'J.B. Phillips New Testament', abbreviation: 'PHILLIPS', language: 'English', languageCode: 'en', year: 1958, type: 'paraphrase', region: 'Global' },
  // SPANISH
  { id: 'RVR1960', name: 'Reina-Valera 1960', abbreviation: 'RVR1960', language: 'Spanish', languageCode: 'es', year: 1960, type: 'formal', region: 'Latin America' },
  { id: 'RVR1909', name: 'Reina-Valera 1909', abbreviation: 'RVR1909', language: 'Spanish', languageCode: 'es', year: 1909, type: 'formal', region: 'Latin America' },
  { id: 'RVR1995', name: 'Reina-Valera 1995', abbreviation: 'RVR1995', language: 'Spanish', languageCode: 'es', year: 1995, type: 'formal', region: 'Latin America' },
  { id: 'NVI', name: 'Nueva Version Internacional', abbreviation: 'NVI', language: 'Spanish', languageCode: 'es', year: 1999, type: 'dynamic', region: 'Latin America' },
  { id: 'LBLA', name: 'La Biblia de las Americas', abbreviation: 'LBLA', language: 'Spanish', languageCode: 'es', year: 1997, type: 'formal', region: 'Latin America' },
  { id: 'DHH', name: 'Dios Habla Hoy', abbreviation: 'DHH', language: 'Spanish', languageCode: 'es', year: 1979, type: 'dynamic', region: 'Latin America' },
  { id: 'NBD', name: 'Nueva Biblia al Dia', abbreviation: 'NBD', language: 'Spanish', languageCode: 'es', year: 2008, type: 'dynamic', region: 'Latin America' },
  { id: 'PDT', name: 'Palabra de Dios para Todos', abbreviation: 'PDT', language: 'Spanish', languageCode: 'es', year: 2012, type: 'dynamic', region: 'Latin America' },
  // PORTUGUESE
  { id: 'ARC', name: 'Almeida Revista e Corrigida', abbreviation: 'ARC', language: 'Portuguese', languageCode: 'pt', year: 1959, type: 'formal', region: 'Brazil/Portugal' },
  { id: 'ARA', name: 'Almeida Revista e Atualizada', abbreviation: 'ARA', language: 'Portuguese', languageCode: 'pt', year: 1993, type: 'formal', region: 'Brazil/Portugal' },
  { id: 'NVI-PT', name: 'Nova Versao Internacional', abbreviation: 'NVI-PT', language: 'Portuguese', languageCode: 'pt', year: 2000, type: 'dynamic', region: 'Brazil' },
  { id: 'NAA', name: 'Nova Almeida Atualizada', abbreviation: 'NAA', language: 'Portuguese', languageCode: 'pt', year: 2017, type: 'formal', region: 'Brazil' },
  // FRENCH
  { id: 'LSG', name: 'Louis Segond 1910', abbreviation: 'LSG', language: 'French', languageCode: 'fr', year: 1910, type: 'formal', region: 'France/Belgium' },
  { id: 'NBS', name: 'Nouvelle Bible Segond', abbreviation: 'NBS', language: 'French', languageCode: 'fr', year: 2002, type: 'formal', region: 'France' },
  { id: 'BDS', name: 'Bible du Semeur', abbreviation: 'BDS', language: 'French', languageCode: 'fr', year: 2000, type: 'dynamic', region: 'France' },
  { id: 'TOB', name: 'Traduction Oecumenique de la Bible', abbreviation: 'TOB', language: 'French', languageCode: 'fr', year: 1972, type: 'formal', region: 'France' },
  // GERMAN
  { id: 'LUTH', name: 'Lutherbibel 2017', abbreviation: 'LUTH', language: 'German', languageCode: 'de', year: 2017, type: 'formal', region: 'Germany' },
  { id: 'LUTH1545', name: 'Lutherbibel 1545', abbreviation: 'LUTH1545', language: 'German', languageCode: 'de', year: 1545, type: 'formal', region: 'Germany' },
  { id: 'ELB', name: 'Elberfelder Bibel', abbreviation: 'ELB', language: 'German', languageCode: 'de', year: 1871, type: 'literal', region: 'Germany' },
  { id: 'SCH', name: 'Schlachter 2000', abbreviation: 'SCH', language: 'German', languageCode: 'de', year: 2000, type: 'formal', region: 'Germany' },
  { id: 'GNB', name: 'Gute Nachricht Bibel', abbreviation: 'GNB', language: 'German', languageCode: 'de', year: 1982, type: 'dynamic', region: 'Germany' },
  // ITALIAN
  { id: 'NR', name: 'Nuova Riveduta', abbreviation: 'NR', language: 'Italian', languageCode: 'it', year: 1994, type: 'formal', region: 'Italy' },
  { id: 'CEI', name: 'Conferenza Episcopale Italiana', abbreviation: 'CEI', language: 'Italian', languageCode: 'it', year: 2008, type: 'formal', region: 'Italy' },
  // DUTCH
  { id: 'STV', name: 'Statenvertaling', abbreviation: 'STV', language: 'Dutch', languageCode: 'nl', year: 1637, type: 'formal', region: 'Netherlands' },
  { id: 'HSV', name: 'Herziene Statenvertaling', abbreviation: 'HSV', language: 'Dutch', languageCode: 'nl', year: 2010, type: 'formal', region: 'Netherlands' },
  { id: 'NBV', name: 'Nieuwe Bijbelvertaling', abbreviation: 'NBV', language: 'Dutch', languageCode: 'nl', year: 2004, type: 'dynamic', region: 'Netherlands' },
  // JAPANESE
  { id: 'JCB', name: '新共同訳 (New Common Bible)', abbreviation: 'JCB', language: 'Japanese', languageCode: 'ja', year: 1987, type: 'formal', region: 'Japan' },
  { id: 'JKG', name: '口語訳 (Colloquial Translation)', abbreviation: 'JKG', language: 'Japanese', languageCode: 'ja', year: 1955, type: 'dynamic', region: 'Japan' },
  { id: 'JNKJ', name: '新改訳2017 (New Interconfessional)', abbreviation: 'JNKJ', language: 'Japanese', languageCode: 'ja', year: 2017, type: 'formal', region: 'Japan' },
  // KOREAN
  { id: 'KGRV', name: '개역개정 (Korean Revised)', abbreviation: 'KGRV', language: 'Korean', languageCode: 'ko', year: 1998, type: 'formal', region: 'Korea' },
  { id: 'KHG', name: '개역한글 (Korean Hangul)', abbreviation: 'KHG', language: 'Korean', languageCode: 'ko', year: 1956, type: 'formal', region: 'Korea' },
  { id: 'KCD', name: '공동번역 (Common Translation)', abbreviation: 'KCD', language: 'Korean', languageCode: 'ko', year: 1977, type: 'formal', region: 'Korea' },
  // CHINESE
  { id: 'CUV', name: '和合本 (Chinese Union Version)', abbreviation: 'CUV', language: 'Chinese', languageCode: 'zh', year: 1919, type: 'formal', region: 'China/Taiwan' },
  { id: 'CNV', name: '新译本 (Chinese New Version)', abbreviation: 'CNV', language: 'Chinese', languageCode: 'zh', year: 1992, type: 'formal', region: 'Taiwan/HK' },
  { id: 'CNET', name: '当代译本 (Contemporary Chinese)', abbreviation: 'CNET', language: 'Chinese', languageCode: 'zh', year: 1979, type: 'dynamic', region: 'China' },
  // TAGALOG/FILIPINO
  { id: 'ASD', name: 'Ang Salita ng Diyos', abbreviation: 'ASD', language: 'Tagalog', languageCode: 'tl', year: 2009, type: 'formal', region: 'Philippines' },
  { id: 'MBB', name: 'Magandang Balita Biblia', abbreviation: 'MBB', language: 'Tagalog', languageCode: 'tl', year: 2005, type: 'dynamic', region: 'Philippines' },
  { id: 'APD', name: 'Ang Pulong Sa Dios', abbreviation: 'APD', language: 'Cebuano', languageCode: 'ceb', year: 2009, type: 'dynamic', region: 'Philippines' },
  // HINDI
  { id: 'HINIRV', name: 'Hindi Bible (IRV)', abbreviation: 'HINIRV', language: 'Hindi', languageCode: 'hi', year: 2019, type: 'formal', region: 'India' },
  { id: 'HINBSI', name: 'Hindi BSI Bible', abbreviation: 'HINBSI', language: 'Hindi', languageCode: 'hi', year: 1977, type: 'formal', region: 'India' },
  // INDONESIAN
  { id: 'TB', name: 'Terjemahan Baru', abbreviation: 'TB', language: 'Indonesian', languageCode: 'id', year: 1974, type: 'formal', region: 'Indonesia' },
  { id: 'TSI', name: 'Terjemahan Sederhana Indonesia', abbreviation: 'TSI', language: 'Indonesian', languageCode: 'id', year: 2017, type: 'dynamic', region: 'Indonesia' },
  // ARABIC
  { id: 'ARVD', name: 'Arabic Van Dyck', abbreviation: 'ARVD', language: 'Arabic', languageCode: 'ar', year: 1865, type: 'formal', region: 'Middle East' },
  { id: 'ARSVD', name: 'Arabic Smith Van Dyke', abbreviation: 'ARSVD', language: 'Arabic', languageCode: 'ar', year: 1860, type: 'formal', region: 'Middle East' },
  // RUSSIAN
  { id: 'RUSV', name: 'Russian Synodal Version', abbreviation: 'RUSV', language: 'Russian', languageCode: 'ru', year: 1876, type: 'formal', region: 'Russia' },
  // SWAHILI
  { id: 'SWSUV', name: 'Swahili Union Version', abbreviation: 'SWSUV', language: 'Swahili', languageCode: 'sw', year: 1952, type: 'formal', region: 'East Africa' },
  // AMHARIC
  { id: 'AMH', name: 'Amharic Bible', abbreviation: 'AMH', language: 'Amharic', languageCode: 'am', year: 1935, type: 'formal', region: 'Ethiopia' },
  // ORIGINAL LANGUAGES
  { id: 'BHS', name: 'Biblia Hebraica Stuttgartensia', abbreviation: 'BHS', language: 'Biblical Hebrew', languageCode: 'he', year: 1977, type: 'literal', region: 'Academic' },
  { id: 'LXX', name: 'Septuagint Greek', abbreviation: 'LXX', language: 'Greek', languageCode: 'el-anc', year: -250, type: 'literal', region: 'Academic' },
  { id: 'GNT', name: 'Greek New Testament', abbreviation: 'GNT', language: 'Koine Greek', languageCode: 'el-anc', year: 100, type: 'literal', region: 'Academic' },
  { id: 'VULG', name: 'Latin Vulgate', abbreviation: 'VULG', language: 'Latin', languageCode: 'la', year: 405, type: 'literal', region: 'Academic' },
  // SCANDINAVIAN
  { id: 'SFB', name: 'Svenska Folkbibeln', abbreviation: 'SFB', language: 'Swedish', languageCode: 'sv', year: 1998, type: 'formal', region: 'Sweden' },
  { id: 'BIBL2000', name: 'Bibel 2000', abbreviation: 'BIBL2000', language: 'Swedish', languageCode: 'sv', year: 2000, type: 'formal', region: 'Sweden' },
  { id: 'NB', name: 'Norsk Bibel', abbreviation: 'NB', language: 'Norwegian', languageCode: 'no', year: 1988, type: 'formal', region: 'Norway' },
  { id: 'BIBL2011', name: 'Bibelen 2011', abbreviation: 'BIBL2011', language: 'Norwegian', languageCode: 'no', year: 2011, type: 'formal', region: 'Norway' },
  // SLAVIC
  { id: 'UKRCULV', name: 'Ukrainian Kulish', abbreviation: 'UKRCULV', language: 'Ukrainian', languageCode: 'uk', year: 1903, type: 'formal', region: 'Ukraine' },
  { id: 'POLISH', name: 'Biblia Tysiaclecia', abbreviation: 'POLISH', language: 'Polish', languageCode: 'pl', year: 1965, type: 'formal', region: 'Poland' },
  { id: 'CZECH', name: 'Bible Kralicka', abbreviation: 'CZECH', language: 'Czech', languageCode: 'cs', year: 1613, type: 'formal', region: 'Czech Republic' },
  // AFRICAN LANGUAGES
  { id: 'YORUBA', name: 'Yoruba Bible', abbreviation: 'YORUBA', language: 'Yoruba', languageCode: 'yo', year: 1900, type: 'formal', region: 'Nigeria' },
  { id: 'HAUSA', name: 'Hausa Bible', abbreviation: 'HAUSA', language: 'Hausa', languageCode: 'ha', year: 1932, type: 'formal', region: 'Nigeria/Niger' },
  { id: 'IGBO', name: 'Igbo Bible', abbreviation: 'IGBO', language: 'Igbo', languageCode: 'ig', year: 1906, type: 'formal', region: 'Nigeria' },
  { id: 'ZULU', name: 'Zulu Bible', abbreviation: 'ZULU', language: 'Zulu', languageCode: 'zu', year: 1986, type: 'formal', region: 'South Africa' },
  { id: 'XHOSA', name: 'Xhosa Bible', abbreviation: 'XHOSA', language: 'Xhosa', languageCode: 'xh', year: 1975, type: 'formal', region: 'South Africa' },
  { id: 'AFRIK', name: 'Afrikaans Bible', abbreviation: 'AFRIK', language: 'Afrikaans', languageCode: 'af', year: 1983, type: 'formal', region: 'South Africa' },
  // SOUTH ASIAN
  { id: 'TELUGU', name: 'Telugu Bible', abbreviation: 'TELUGU', language: 'Telugu', languageCode: 'te', year: 1880, type: 'formal', region: 'India' },
  { id: 'TAMIL', name: 'Tamil Bible', abbreviation: 'TAMIL', language: 'Tamil', languageCode: 'ta', year: 1886, type: 'formal', region: 'India/Sri Lanka' },
  { id: 'KANNADA', name: 'Kannada Bible', abbreviation: 'KANNADA', language: 'Kannada', languageCode: 'kn', year: 1986, type: 'formal', region: 'India' },
  { id: 'MALAYALAM', name: 'Malayalam Bible', abbreviation: 'MALAYALAM', language: 'Malayalam', languageCode: 'ml', year: 1910, type: 'formal', region: 'India' },
  { id: 'MARATHI', name: 'Marathi Bible', abbreviation: 'MARATHI', language: 'Marathi', languageCode: 'mr', year: 1820, type: 'formal', region: 'India' },
  { id: 'BENGALI', name: 'Bengali Bible', abbreviation: 'BENGALI', language: 'Bengali', languageCode: 'bn', year: 1832, type: 'formal', region: 'Bangladesh/India' },
  { id: 'URDU', name: 'Urdu Bible', abbreviation: 'URDU', language: 'Urdu', languageCode: 'ur', year: 1843, type: 'formal', region: 'Pakistan/India' },
  { id: 'PUNJABI', name: 'Punjabi Bible', abbreviation: 'PUNJABI', language: 'Punjabi', languageCode: 'pa', year: 1811, type: 'formal', region: 'India/Pakistan' },
  // SOUTHEAST ASIAN
  { id: 'THAI', name: 'Thai Bible', abbreviation: 'THAI', language: 'Thai', languageCode: 'th', year: 1971, type: 'formal', region: 'Thailand' },
  { id: 'VIETNAMESE', name: 'Vietnamese Bible', abbreviation: 'VIETNAMESE', language: 'Vietnamese', languageCode: 'vi', year: 1926, type: 'formal', region: 'Vietnam' },
  { id: 'KHMER', name: 'Khmer Bible', abbreviation: 'KHMER', language: 'Khmer', languageCode: 'km', year: 1954, type: 'formal', region: 'Cambodia' },
  { id: 'BURMESE', name: 'Burmese Bible', abbreviation: 'BURMESE', language: 'Burmese', languageCode: 'my', year: 1835, type: 'formal', region: 'Myanmar' },
  { id: 'MALAY', name: 'Malay Bible', abbreviation: 'MALAY', language: 'Malay', languageCode: 'ms', year: 1998, type: 'formal', region: 'Malaysia' },
];

export const HIGHLIGHT_COLORS = [
  { name: 'Golden', value: '#FEF08A', light: '#FEFCE8', text: '#854D0E' },
  { name: 'Rose', value: '#FDA4AF', light: '#FFF1F2', text: '#9F1239' },
  { name: 'Sky', value: '#7DD3FC', light: '#F0F9FF', text: '#075985' },
  { name: 'Mint', value: '#86EFAC', light: '#F0FDF4', text: '#166534' },
  { name: 'Lavender', value: '#C4B5FD', light: '#FAF5FF', text: '#5B21B6' },
  { name: 'Peach', value: '#FDBA74', light: '#FFF7ED', text: '#9A3412' },
  { name: 'Cyan', value: '#67E8F9', light: '#ECFEFF', text: '#155E75' },
  { name: 'Lime', value: '#BEF264', light: '#F7FEE7', text: '#3F6212' },
];

export const FONT_FAMILIES = [
  { name: 'Lora', value: 'Lora, serif', category: 'Serif', googleFont: 'Lora' },
  { name: 'Playfair Display', value: "'Playfair Display', serif", category: 'Serif', googleFont: 'Playfair+Display' },
  { name: 'Merriweather', value: 'Merriweather, serif', category: 'Serif', googleFont: 'Merriweather' },
  { name: 'Georgia', value: 'Georgia, serif', category: 'Serif' },
  { name: 'Inter', value: 'Inter, sans-serif', category: 'Sans-Serif', googleFont: 'Inter' },
  { name: 'Open Sans', value: "'Open Sans', sans-serif", category: 'Sans-Serif', googleFont: 'Open+Sans' },
  { name: 'Nunito', value: 'Nunito, sans-serif', category: 'Sans-Serif', googleFont: 'Nunito' },
  { name: 'Poppins', value: 'Poppins, sans-serif', category: 'Sans-Serif', googleFont: 'Poppins' },
  { name: 'Roboto', value: 'Roboto, sans-serif', category: 'Sans-Serif', googleFont: 'Roboto' },
  { name: 'Source Serif 4', value: "'Source Serif 4', serif", category: 'Serif', googleFont: 'Source+Serif+4' },
  { name: 'Crimson Text', value: "'Crimson Text', serif", category: 'Serif', googleFont: 'Crimson+Text' },
  { name: 'EB Garamond', value: "'EB Garamond', serif", category: 'Serif', googleFont: 'EB+Garamond' },
  { name: 'Libre Baskerville', value: "'Libre Baskerville', serif", category: 'Serif', googleFont: 'Libre+Baskerville' },
  { name: 'Cinzel', value: 'Cinzel, serif', category: 'Display', googleFont: 'Cinzel' },
  { name: 'Cormorant Garamond', value: "'Cormorant Garamond', serif", category: 'Serif', googleFont: 'Cormorant+Garamond' },
  { name: 'Dancing Script', value: "'Dancing Script', cursive", category: 'Script', googleFont: 'Dancing+Script' },
  { name: 'Sacramento', value: 'Sacramento, cursive', category: 'Script', googleFont: 'Sacramento' },
  { name: 'Pacifico', value: 'Pacifico, cursive', category: 'Script', googleFont: 'Pacifico' },
  { name: 'OpenDyslexic', value: 'OpenDyslexic, sans-serif', category: 'Accessibility' },
  { name: 'Atkinson Hyperlegible', value: "'Atkinson Hyperlegible', sans-serif", category: 'Accessibility', googleFont: 'Atkinson+Hyperlegible' },
];

export const WORSHIP_ARTISTS = [
  // MAJOR WORSHIP MOVEMENTS
  { id: 'hillsong-united', name: 'Hillsong United', origin: 'Australia', genre: 'Contemporary Worship', youtube: 'UCN7UE7gCONXw6b-B1AyZhOQ' },
  { id: 'hillsong-worship', name: 'Hillsong Worship', origin: 'Australia', genre: 'Contemporary Worship', youtube: 'UC-2PJwM80dVFz7LFnLjcZcQ' },
  { id: 'bethel-music', name: 'Bethel Music', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCvfBTZkXNkB_DEr04rFHbAQ' },
  { id: 'elevation-worship', name: 'Elevation Worship', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCnBuKuWiVMJXMJEKEh_lrFA' },
  { id: 'planetshakers', name: 'Planetshakers', origin: 'Australia', genre: 'Pentecostal Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'victory-worship', name: 'Victory Worship', origin: 'Philippines', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'awaken84', name: 'Awake84', origin: 'Philippines', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'vertical-worship', name: 'Vertical Worship', origin: 'USA', genre: 'Reformed Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'maverick-city', name: 'Maverick City Music', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCgW7oqMJBOtHPKUQzfhiUhA' },
  { id: 'christomlin', name: 'Chris Tomlin', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'matt-redman', name: 'Matt Redman', origin: 'UK', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'tim-hughes', name: 'Tim Hughes', origin: 'UK', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'delirious', name: 'Delirious?', origin: 'UK', genre: 'Rock Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'rend-collective', name: 'Rend Collective', origin: 'Ireland', genre: 'Folk Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'gateway-worship', name: 'Gateway Worship', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'passion', name: 'Passion', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'tomfenton', name: 'Tom Fenton', origin: 'Australia', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'cory-asbury', name: 'Cory Asbury', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'will-reagan', name: 'Will Reagan', origin: 'USA', genre: 'Acoustic Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'upperroom', name: 'UPPERROOM', origin: 'USA', genre: 'Spontaneous Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'jesus-culture', name: 'Jesus Culture', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'kari-jobe', name: 'Kari Jobe', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'crowder', name: 'Crowder', origin: 'USA', genre: 'Folk Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'phil-wickham', name: 'Phil Wickham', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'natalie-grant', name: 'Natalie Grant', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'tauren-wells', name: 'Tauren Wells', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'aaron-shust', name: 'Aaron Shust', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'jeremy-camp', name: 'Jeremy Camp', origin: 'USA', genre: 'Rock Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'toby-mac', name: 'TobyMac', origin: 'USA', genre: 'CCM', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'lauren-daigle', name: 'Lauren Daigle', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'for-king-country', name: 'for KING & COUNTRY', origin: 'Australia', genre: 'CCM', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'newsboys', name: 'Newsboys', origin: 'Australia', genre: 'CCM', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'skillet', name: 'Skillet', origin: 'USA', genre: 'Christian Rock', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'switchfoot', name: 'Switchfoot', origin: 'USA', genre: 'Christian Rock', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'third-day', name: 'Third Day', origin: 'USA', genre: 'Southern Rock Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'casting-crowns', name: 'Casting Crowns', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'michael-w-smith', name: 'Michael W. Smith', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'don-moen', name: 'Don Moen', origin: 'USA', genre: 'Traditional Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'paul-baloche', name: 'Paul Baloche', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'darlene-zschech', name: 'Darlene Zschech', origin: 'Australia', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'robin-mark', name: 'Robin Mark', origin: 'Ireland', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'travis-cottrell', name: 'Travis Cottrell', origin: 'USA', genre: 'Traditional Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'david-crowder', name: 'David Crowder Band', origin: 'USA', genre: 'Alternative Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'rock-church', name: 'Rock Church Worship', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'highlands-worship', name: 'Highlands Worship', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'life-worship', name: 'Life.Church Worship', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'elevation-rhythm', name: 'Elevation Rhythm', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'church-motion', name: 'Church Motion', origin: 'USA', genre: 'Electronic Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'icf-worship', name: 'ICF Worship', origin: 'Switzerland', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'bethel-next', name: 'Bethel Next', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'zach-williams', name: 'Zach Williams', origin: 'USA', genre: 'Country Gospel', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'brandon-lake', name: 'Brandon Lake', origin: 'USA', genre: 'Contemporary Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'dante-bowe', name: 'Dante Bowe', origin: 'USA', genre: 'Gospel Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
  { id: 'jonathan-traylor', name: 'Jonathan Traylor', origin: 'USA', genre: 'Gospel Worship', youtube: 'UCsXmH4dE_DW3DJPVBHFPN3A' },
];

export const POPULAR_WORSHIP_SONGS = [
  { id: 'w1', title: 'Oceans (Where Feet May Fail)', artist: 'Hillsong United', youtubeId: 'dy9nwe9-mpU', lyrics: 'You call me out upon the waters...' },
  { id: 'w2', title: 'What a Beautiful Name', artist: 'Hillsong Worship', youtubeId: 'nQWFzMaT_aA', lyrics: 'You were the Word at the beginning...' },
  { id: 'w3', title: 'Reckless Love', artist: 'Cory Asbury', youtubeId: 'Sc6SSHuZvQE', lyrics: 'Before I spoke a word, You were singing over me...' },
  { id: 'w4', title: 'Way Maker', artist: 'Sinach', youtubeId: 'iovu9O-GHIY', lyrics: 'You are here, moving in our midst...' },
  { id: 'w5', title: 'Raise a Hallelujah', artist: 'Bethel Music', youtubeId: 'OPYoRGqEY_k', lyrics: 'I raise a hallelujah, in the presence of my enemies...' },
  { id: 'w6', title: 'Goodness of God', artist: 'Bethel Music', youtubeId: 'XcaDMBWbsYA', lyrics: 'I love You Lord, Oh Your mercy never fails me...' },
  { id: 'w7', title: 'Build My Life', artist: 'Pat Barrett', youtubeId: 'yNQBrMp9XtM', lyrics: 'Worthy of every song we could ever sing...' },
  { id: 'w8', title: 'Do It Again', artist: 'Elevation Worship', youtubeId: 'yOJrPFaBGzQ', lyrics: 'Walking around these walls...' },
  { id: 'w9', title: 'O Come to the Altar', artist: 'Elevation Worship', youtubeId: 'PoARFSO2vBM', lyrics: 'Are you hurting and broken within...' },
  { id: 'w10', title: 'Who You Say I Am', artist: 'Hillsong Worship', youtubeId: 'gROTHKxHIaI', lyrics: 'Who am I that the highest King would welcome me?...' },
  { id: 'w11', title: 'Living Hope', artist: 'Phil Wickham', youtubeId: 'gOuFVqJh0eQ', lyrics: 'How great the chasm that lay between us...' },
  { id: 'w12', title: 'The Blessing', artist: 'Elevation Worship', youtubeId: 'svFdaqtWnXA', lyrics: 'The Lord bless you and keep you...' },
  { id: 'w13', title: 'Holy Spirit', artist: 'Bethel Music', youtubeId: 'lUTmPYXPAXY', lyrics: 'There is nothing worth more that will ever come close...' },
  { id: 'w14', title: '10000 Reasons', artist: 'Matt Redman', youtubeId: 'DXDGE_lRI0E', lyrics: 'Bless the Lord, O my soul...' },
  { id: 'w15', title: 'Amazing Grace (My Chains Are Gone)', artist: 'Chris Tomlin', youtubeId: 'XtB0yY5L0eI', lyrics: 'Amazing grace, how sweet the sound...' },
  { id: 'w16', title: 'Yet Not I But Through Christ In Me', artist: 'CityAlight', youtubeId: 'hwc2d1Xt8gM', lyrics: 'What gift of grace is Jesus my redeemer...' },
  { id: 'w17', title: 'King of Kings', artist: 'Hillsong Worship', youtubeId: 'vCIXjOGKNYQ', lyrics: 'In the darkness we were waiting...' },
  { id: 'w18', title: 'Cornerstone', artist: 'Hillsong Worship', youtubeId: '92ox9YMgaB8', lyrics: 'My hope is built on nothing less...' },
  { id: 'w19', title: 'Great Are You Lord', artist: 'All Sons & Daughters', youtubeId: 'bX8hvEuPVKQ', lyrics: 'You give life, You are love...' },
  { id: 'w20', title: 'How Great Is Our God', artist: 'Chris Tomlin', youtubeId: 'KBD18rsVJHk', lyrics: 'The splendor of a King, clothed in majesty...' },
];
